window.actionsData_en = [
	"Hammaste pesemine",
	"Juuste kammimine või harjamine",
	"Näo pesemine",
	"Duši all käimine (keha pesemine)",
	"Rätikuga kuivatamine",
	"Riietumine (riiete selga panemine)",
	"kingapaelte sidumine",
	"Käte pesemine",
	"Söömine (kahvliga/lusikaga)",
	"Tassist joomine",
	"Pliidil keetmine (poti segamine)",
	"Köögiviljade tükeldamine lõikelaual",
	"Supi segamine potis",
	"pannkookide keeramine pannil",
	"Muna praadimine pannil",
	"Toidu maitsmine ja soola lisamine",
	"Nõude pesemine kraanikausis",
	"Nõude kuivatamine rätikuga",
	"Põranda tolmuimeja",
	"Põranda pühkimine luudaga (pantomiimiline pühkimine)",
	"Põranda pühkimine mopiga",
	"Mööbli pühkimine lapiga",
	"Akna puhtaks pühkimine",
	"Prügikasti välja viimine (prügikoti kandmine)",
	"Pesu kokku voltimine (riiete voltimine)",
	"Riiete triikimine triikimislaual",
	"Voodi tegemine (linade laiali panemine)",
	"lambipirni vahetamine üleval",
	"Söögilaua katmine",
	"Lemmiklooma söötmine (toidu valamine kaussi)",
	"Taimede kastmine kastekannuga",
	"Lehtede riisumine õues",
	"Lume labida kõnniteelt",
	"Postkasti kontrollimine posti jaoks",
	"Ukse lukustamine või avamine võtmega",
	"Seina värvimine värvirulliga",
	"Naela löömine seina",
	"Puutüki saagimine",
	"Kruvi pingutamine kruvikeerajaga",
	"Trepile tõusmine (astumine)",
	"Raamatu või ajalehe lugemine",
	"Kirja kirjutamine paberile",
	"Kudumine kudumisvarrastega",
	"Nööbi õmblemine kangale",
	"Otsin midagi diivani alt",
	"Lapse mähkmete vahetamine",
	"Lapsevankri lükkamine",
	"Koeraga jalutamine (rihma käes)",
	"Mänguasjade korjamine põrandalt",
	"Meigi pealekandmine peeglist",
	"Raseerimine habemeajamisvahendiga",
	"Kinnaste selga panemine",
	"Kellaaja kontrollimine käekellast",
	"Fotode tegemine nutitelefoniga",
	"Telefoniga helistamine (telefoni kõrva ääres hoidmine)",
	"Teksti kirjutamine telefoniga (pöidlaga kirjutamine)",
	"Kinnijäänud purgi avamine (kaane keeramisega pingutades)",
	"Kääride kasutamine paberi lõikamiseks",
	"Sokkide jalga panemine",
	"Särgi kinni nööpimine",
	"Jope kokku tõmbamine",
	"Raske/akistunud ukse lahti tõmbamine",
	"Bensiini pumpamine autosse bensiinijaamas",
	"Sularahaga maksmine (raha üleandmine)",
	"Krediitkaardi viipamine poes",
	"sularahaautomaadi kasutamine",
	"Automaadi kasutamine (nuppude vajutamine, eseme väljavõtmine)",
	"Joomine läbi kõrre",
	"Spagetinuudlite lutsutamine",
	"Väljuva bussi taga ajamine",
	"Telerivaatamine (puldi kasutamine kanalite vahetamiseks)",
	"Kanalite surfamine (puldi korduv klõpsamine)",
	"Lauamängu mängimine (täringutega veeretamine, tükikeste liigutamine)",
	"Dokumendi allkirjastamine (allkirja kirjutamine)",
	"Fööni kasutamine juuste kuivatamiseks",
	"Peeglisse vaatamine ja oma juuste või riietuse kohandamine",
	"Kontaktläätsede panemine",
	"Küünte värvimine",
	"Pildiraami seinale riputamine (naela löömine)",
	"Jojo-jooga mängimine",
	"Õhupalli puhumine",
	"Mullpakendi lõhkumine sõrmedega",
	"Hula hoop ümber vöökoha",
	"Toidu mikrolaineahjus küpsetamine ja selle valmimise ootamine",
	"Külmkapist millegi maitsmine ja ahmimine, kui see on halb",
	"Kaelarihma sidumine krae ümber",
	"Jooksmine/jooksmine ühtlases tempos",
	"Hüppeliigeseid teha",
	"Tõukerollide tegemine",
	"Tõmbeid teha (kujutledes kangi üle pea)",
	"Raskuste tõstmine (bicepcurls või hantli tõstmine)",
	"Lihaste painutamine nagu kulturist",
	"Venitamine joogapoosis",
	"Aeroobika/tantsuharjutuste tegemine",
	"Köie hüppamine (hüppetross)",
	"Jalgrattaga sõitmine (pedaalimine ja roolimine)",
	"Ujumine (ujumistrenni tegemine)",
	"Sukeldumine basseini (käed üleval, hüppamine ettepoole)",
	"Suusatamine mäest alla (põlvede painutamine, keppide kasutamine)",
	"Uisutamine (libisemine ja tasakaalustamine, käed väljasirutatud)",
	"Rulluisutamine või rulluisutamine",
	"Rula (jalaga löömine ja laual balansseerimine)",
	"Surfamine lainel (tasakaalustamine nähtamatul lainelaual)",
	"lumelauaga alla nõlva sõitmine",
	"Kaljuronimine seinale (sirutus ja ülespoole astumine)",
	"Matkamine raske seljakotiga",
	"Jalgpalli mängimine (kujuteldava palli driibeldamine ja löömine)",
	"Korvpalli mängimine (kujuteldava palli põrgatamine, viskamine)",
	"Pesapallimängija löömine palli löömiseks",
	"Pesapalliga visata (kerimine ja viskamine)",
	"Tennise mängimine (reketi löömine ees- ja tagakäega)",
	"Tennisepalli servimine (viskamine ja löömine)",
	"Võrkpalli mängimine (palli servimine või löömine)",
	"Golfikepi löömine golfipalliga",
	"Bowling (nähtamatu bowlingupalli veeretamine)",
	"Pingpongi mängimine (lauatennise löökpalli kiikumine)",
	"Jalgpalli viskamine (Ameerika jalgpalli veerandmängija viskamine)",
	"Jalgpalli söödu püüdmine",
	"Frisbee-ketta viskamine",
	"Vibu sihtimine ja noole laskmine (vibulaskmine)",
	"Poks (sparring rusikatega, löögid ja kaitsmine)",
	"Karate või võitluskunstide liigutused (katade või löökide sooritamine)",
	"Vehklemisduell (sportlik mõõgavõitlusasend ja löök)",
	"Vastase maadlemine (maadlemine õhuga)",
	"Tasakaalustamine tasakaalupalgil (käed välja sirutatud tasakaalu saavutamiseks)",
	"Hüppamine batuudil (hüppamine kohapeal)",
	"Köievedu mängimine (nähtamatu köie kõvasti tõmmates)",
	"Ratsutamine (hoovast kinni hoides ja sadulas hüpeldes)",
	"Mehhaanilisel härjal ratsutamine (rodeo stiilis, üks käsi üleval)",
	"Kalapüük (varda viskamine ja sissevedamine)",
	"Takistuste jooksmine (sprint ja takistuse ületamine)",
	"odaheide",
	"Heitmine (ühe õlaga heites)",
	"Kõrgushüppe sooritamine (jooksmine ja hüppamine)",
	"Poksi kiiruskoti löömine (kiire rusikaga)",
	"Köiega ronimine (ronimisliigutus käest-kätte)",
	"Kelgutamine mäest alla (istudes ja kujuteldavat kelku juhtides)",
	"Lumepallilahing (lumepallide pakkimine ja viskamine)",
	"Viskepalli mängimine (palli viskamine ja viskamine)",
	"Piljardi/piljardi mängimine (piljardikiu joondamine ja tulistamine)",
	"Paadiga sõudmine (sõudjate kasutamine sõudmisliigutuses)",
	"Kriketi mängimine (löögi andmine kriketikepiga)",
	"Jäähoki mängimine (hokikepi ja -korvi käsitsemine)",
	"Sulgpalli mängimine (sulgpallimängu löömine labidaga)",
	"Põrkepunkti võidutantsu sooritamine (jalgpalli tähistamine)",
	"Sumomaadleja trampimine ja asendi võtmine",
	"Langevarjuhüpped (vaba langemine ja langevarju köie tõmbamine)",
	"Sukeldumine (ujumine käsiuimedega ja hingamine regulaatori kaudu)",
	"Whitewater rafting (jõuline sõudmine)",
	"veesuusatamine (köie käepidemest kinni hoides ja suuskadel balansseerides)",
	"Seljasõit (hüppamine ettepoole, jalad koos nagu kotis)",
	"Kitarri mängimine (strummi ja akordioni mängimine)",
	"Klaverimäng (klahvide vajutamine mõlema käega)",
	"Viiulimäng (ühe käega vibu, teise käega sõrmitsemine)",
	"Trummide mängimine (trummikomplekti õhutrummimine)",
	"Flöödil mängimine (küljega hoidmine ja sõrmede liigutamine)",
	"Saksofoni mängimine (sõrmede kasutamine ja puhumine saksofoni)",
	"Trompetil mängimine (suupilli sumisemine, klappide vajutamine)",
	"Laulmine mikrofoni abil (mikrofoni hoidmine ja häälega laulmine)",
	"Balletitantsimine (graatsilised keerutused ja käte liigutused)",
	"Tantsimine hip-hop stiilis (vabatantsu liigutused)",
	"Tantsida tantsuvalssi (nähtamatu partneri hoidmine)",
	"Diskotantsimine (sõrmedega õhku näitamine, rütmilised sammud)",
	"Stepptantsimine (kiired koputussammud)",
	"Pildi maalimine lõuendil (pintseldamine lõuendil)",
	"Joonistamine paberile (visandamine pliiatsiga)",
	"savi skulptuurimine (savi vormimine kätega)",
	"Keraamikatööde tegemine keraamilise ratta peal (savi vormimine)",
	"Fotode tegemine fotoaparaadiga (fotoaparaadi hoidmine ja klõpsamine)",
	"Videokaameraga filmimine (õlakaamera, fokuseerimine)",
	"Näitlemine laval (dramaatilise monoloogi esitamine või publikule kummardamine)",
	"Maagilise triki sooritamine (nt kujuteldava jänese väljatõmbamine mütsist)",
	"Kaardipaki segamine (silla segamise liigutus)",
	"Mängukaartide jagamine",
	"Male mängimine (nähtamatu malefiguuri mõtlikult liigutamine)",
	"Videomängude mängimine (keskendumine ja nuppude vajutamine kontrolleril)",
	"Salli kudumine kudumisvarrastega",
	"Õmblusmasina kasutamine (jalga pumbates ja kangast juhtides)",
	"Kalligraafia kirjutamine sulgpliiatsiga",
	"Lillekimbu korrastamine",
	"Pallidega žongleerimine (kujuteldavate pallide viskamine ja püüdmine rütmis)",
	"Žongleerimine keppidega või noaga (ohtlike esemete kujuteldav žongleerimine)",
	"Trossil kõndimine (käed tasakaalustamiseks välja sirutatud, ettevaatlikud sammud)",
	"Ühe jalgrattaga sõitmine (käed välja sirutatud, tasakaalustamine ühe ratta pedaalimise ajal)",
	"Klounina esinemine (suure naeratuse imiteerimine, rumalad liigutused, võib-olla õhupalliloomade tegemine)",
	"Nähtamatus kastis kinni olev pantomiim (klassikaline pantomiimirutiin, seinte tunnetamine)",
	"Näomaaling (kellegi näo värvimine pintsliga - mimika)",
	"DJ, kes segab muusikat (teeseldes plaadimängijaid ja bob pea)",
	"Õhukitarri mängimine (rokkimine ilma pillidel)",
	"Orkestri dirigeerimine (dirigendipuldi taktis lehvitamine)",
	"Akordioni mängimine (tõukamine ja tõmbamine, klahvide vajutamine)",
	"Origamipaberi voltimine (nähtamatu paberi keerukas voltimine)",
	"Lasso kasutamine (kujuteldava lasso keerutamine pea kohal)",
	"Karikatuuride joonistamine (karikatuuritegelase joonistamine paberile)",
	"Stand-up-komöödia esitamine (naljade esitamine väljenduslike žestidega)",
	"Ventriloogiaaktus (nukkude suu liigutamine "vaikides")",
	"Rubiku kuubiku lahendamine (nähtamatu kuubiku kiire keeramine)",
	"Noolega mängimine (noolega sihtimine ja viskamine, seejärel reageerimine)",
	"Hüppetõkke mängimine (hüppamine läbi kujuteldavate kriidiruutude)",
	"Autoga sõitmine (rooliga sõitmine, käikude vahetamine)",
	"Bussiga sõitmine (suur rool, ukse avamine)",
	"Kahveltõstuki juhtimine (hoobade käsitsemine ja ettevaatlik sõitmine)",
	"Lennukiga lendamine (rooli hoidmine, lülitite keeramine)",
	"Laeva juhtimine (suure laeva rooli keeramine)",
	"Kaevamine labidaga (mulla kühveldamine ja viskamine)",
	"Naela löömine (ehitustööd)",
	"Puidu saagimine käsisaega",
	"Puurimine seina sisse elektripuuriga",
	"Poldi pingutamine mutrivõtmega",
	"Vasara käsitsemine (kogu keha vibreerimine)",
	"Metalli keevitamine (keevitusriista ja kaitsevisiiri imiteerimine)",
	"WC-sse sukeldumine (kasutades jõuliselt pumbaga)",
	"Posti kättetoimetamine (kõndimine ja posti kastidesse panemine)",
	"Lehmade lüpsmine (istudes väljaheitel, tõmmates kujuteldavat udarat)",
	"Puude tükeldamine kirvega",
	"Traktoriga sõitmine talus",
	"Karja karjatamine (vilistades ja kujuteldava lassoga vehkides)",
	"Klaviatuuril kirjutamine (sõrmede kiire liikumine)",
	"Kirjutamine klambril või märkmikul",
	"Telefonikõnele vastamine (kontoritelefon kõrvuni)",
	"Dokumentide arhiveerimine arhiivikappi",
	"Fotokopiate tegemine (koopiamasinate nupu vajutamine, ootaminevamine)",
	"paberite purustamine purustusseadmes",
	"Esitluse pidamine (näitamine kujuteldavale ekraanile või diagrammile)",
	"Kemikaalide segamine keeduklaasides (teadlase roll)",
	"Mikroskoobi vaatamine",
	"Uurimine luubiga (detektiivi roll)",
	"Liikluse juhtimine (käesignaalide kasutamine autode peatamiseks/käigu peatamiseks)",
	"Pilli puhumine (kohtunik või politsei - vaikne puhumine, kuid žestidega puhumine ja osutamine)",
	"Kahtlustatava käeraudade kinnitamine (randmetest kinni hoidmine ja käeraudade klõpsamine)",
	"Parkimispileti kirjutamine märkmikusse",
	"Tervitamine (sõjaväeline tervitus)",
	"Kohapeal marssimine (sõduri drillimine)",
	"Kellegi skaneerimine metallidetektoriga (turvamees)",
	"Vee pihustamine tuletõrjevoolikust (tuletõrjuja)",
	"Redelile ronimine (tuletõrjuja või tööline ronib redelil)",
	"Kellegi õlgadel ohutusse kohta kandmine (tuletõrjuja kandmine kujuteldava isikuga)",
	"Operatsiooni teostamine (patsiendi ettevaatlik instrumentide kasutamine)",
	"südamelöögi kuulamine stetoskoobiga (arstlik läbivaatus)",
	"Süsti andmine süstlaga (meditsiiniõde või arst)",
	"Patsiendi temperatuuri kontrollimine (termomeeter keele all)",
	"Kirurgiliste kinnaste ja maski selga panemine (kinnaste kinnas)",
	"Keegi vererõhu mõõtmine (manseti mähkimine, pumba pigistamine)",
	"Kiirabiautoga sõitmine (sireenide helisev liikumine)",
	"Rongipilli nööri tõmbamine (vedurijuht)",
	"Piletite löömine rongil (rongijuht)",
	"baarmen (kokteilisegisti raputamine, klaasi valamine)",
	"Joogi valamine pudelist klaasi",
	"Toidu serveerimine kandikul (kelner, kes tasakaalustab kandikuid)",
	"Wokis praadimine (kokk viskab toitu pannil)",
	"Pitsataina õhku viskamine (pitsakokk)",
	"Supi maitsmine kokana (lonks ja heakskiitmine või soola lisamine)",
	"Juuste lõikamine kääride ja kammiga (juuksur)",
	"Lehtede puhumise kasutamine õues (aednik)",
	"Muru niitmine tõukuriga",
	"Puu langetamine kahekäelise sae või kirvega",
	"Fotode tegemine üritusel (professionaalne fotograaf kaameraga)",
	"Kõne või loengu pidamine (poliitik või professor žestidega)",
	"Vasara löömine (kohtunik kohtusaalis)",
	"Ohutusjuhiste demonstreerimine lennukis (lennujuhi mimika turvavööga, hapnikumaskiga)",
	"Nulligravitatsioonis hõljumine astronautina (aeglased liigutused, enda kinnipanemine)",
	"Hamba väljatõmbamine (hambaarst liigutab ja tõmbab nähtamatut hammast, näitab seda)",
	"Lemmiklooma uurimine (veterinaararst kontrollib koera või kassi)",
	"Raamatute riiulitele panemine (raamatukoguhoidja asetab raamatud kõrgele riiulile)",
	"Kaupade skaneerimine kassas (kassapidaja piiksutab kaupu)",
	"Turvalisuse kontrollpuldi kasutamine lennujaama turvakontrollis (isiku skaneerimine)",
	"Töö konveieril (ülesande kiire kordamine kujuteldaval konveieril)",
	"Selfie-video tegemine sotsiaalmeedia jaoks (mõjutaja poseerib telefoniga)",
	"Putukate tõrjumine (putukamürkide pihustamine nurkadesse paagipihustiga)",
	"Suhtlemine viipekeeles (žestidega nagu kasutaks ASL-i)",
	"Karbi pakkimine saatmiseks (pappkarbi teipimine)",
	"Elustamiskõlbliku elustamise teostamine (rindkere kompressioonid nähtamatule inimesele)",
	"Raha lugemine (pangakassapidaja sirvib arveid)",
	"Kellegi suure kallistuse andmine",
	"Enda tuulutamine, sest on palav",
	"Köhimine käe või küünarnuki sisse",
	"Hikitamine (õlgade tõmblemine)",
	"Juhuslik vilistamine (huulte kortsutamine, kuigi heli ei kostu)",
	"Päevaliselt unistades vahtimine (pilvistes pilvedes väljend)",
	"Uinumine käed väljasirutatud käega",
	"Kellegi seljas ratsutamine (kujuteldava inimese kandmine seljas)",
	"Muusika saatel või tunnustuseks sõrmedega naksutamine",
	"Käte laperdamine ja kurgutamine nagu kana",
	"Lendamine nagu lind (tiibade lehvitamine ja hõljumine)",
	"Hingeldamine ja kerjamine nagu koer (keel välja, käpad üles)",
	"Venitades ja pikutades nagu kass (lakub käppa, kallutab selga)",
	"Galoppimine nagu hobune (kätega plaksutades jäljendab kabjad, hõiskab vaikselt)",
	"Nuusutamine ja oigamine nagu siga (nina jäljendamine)",
	"Sumisemine ja lendamine nagu mesilane (kasutades sõrme nõelana)",
	"Libisemine nagu liblikas (õrnad tiibade liigutused)",
	"Vares nagu kukk hommikul (käed kui nokk)",
	"Hüppab veest välja nagu delfiin",
	"Plaksutamine ja haukumine nagu hüljes (käte kokkupõrkamine)",
	"Tormamine raskete sammude ja pisikeste kätega nagu T-Rexi dinosaurus",
	"Karbis lõksus (tunneb seinu enda ümber)",
	"Köiega tõmmates (köievedu nähtamatu jõu vastu)",
	"Climbing an ladder (sirutus ja astumine)",
	"Leaning an wall (seina mimimine koomilise efekti saavutamiseks)",
	"Kõndimine vastu tugevat tuult (tõukamine ettepoole, keha nurga all)",
	"Kuumadel söedel kõndimine (kiiresti varvastele astudes, jalga valusalt raputades)",
	"Banaanikoore peal libastumine (suur koomiline kukkumisest taastumine)",
	"Astumine millelegi teravale (hüppamine ja hüppamine valusalt)",
	"Väga raske eseme kandmine (raskuse all kõhklemine, pingutamine)",
	"Äärmiselt raske raskuse tõstmine (jõumehe katse, käte värisemine)",
	"Püüa tõsta midagi liiga rasket ja lasta see äkki maha",
	"Midagi tõstmine, mis osutub väga kergeks (ülestõmbamine ja komistamine)",
	"Suure koera poolt rihma otsa tõmmates ettepoole tõmmamine",
	"Omaenda saba taga ajamine (mänguliselt ringiratast keerates)",
	"Sõrme ukse vahele jäämine (käe tagasi tõmbamine, raputamine)",
	"Ümberringi meeletult sumiseva mesilase peksmine",
	"Kõrgele köiel kõndimine (käed välja sirutatud, ettevaatlikult kõndides)",
	"Raamatu tasakaalustamine pea peal kõndides",
	"pallidega žongleerimine (viskamine ja püüdmine ilma rekvisiitideta)",
	"Ratsutamine võluvaibaga (istudes, kujuteldavat vaipa juhtides)",
	"Luudakepil lendamine (nagu oleksite nõid/võidur, kes lendab)",
	"Jetpacki kasutamine (kinnirihmimine ja õhku laskmine, ebastabiilne hõljumine)",
	"Moonwalk-tantsu sooritamine (sujuvalt tagasi libisemine)",
	"Jooksmine aegluubis (liialdatud aeglane jooksmine ja näoga jooksmine)",
	"Tagurpidi liikumine, nagu oleks video tagasi keritud",
	"Tegutsemine nagu nöörile kinnitatud marionett (hüplikud, kontrollitud liigutused ülevalt)",
	"Koomiline elektrilöögi saamine (värisemine ja püsti seisvad juuksed)",
	"Õhupalli lõhkumine, kuni see plahvatab (suur ootamatu üllatusreaktsioon)",
	"Teesklemine, et kahaneb tillukeseks (madalamale kükitamine, ülespoole vaatamine)",
	"Teesklemine, et kasvab hiiglaslikuks (kõrgele sirutades, raskelt astudes)",
	"Läbi paksu tarretise või muda kõndimine (liialdatud vastupanu liikumisel)",
	"Ajapommi kahjutuks tegemine (juhtmete ettevaatlik kärpimine, pingelised näoilmed)",
	"Üksinda köievedu mängimine (nähtamatu köie tõmbamine, siis tõmmatakse edasi)",
	"Nulligravitatsioonis hõljumine (aeglased, triivivad liigutused)",
	"Võitlus aegluubis (löökide viskamine ja aeglaselt kõrvalehoidmine)",
	"Draamliku minestuse sooritamine (käsi otsaesisel, aeglane kokkuvarisemine)",
	"Kujuteldava kinkekarbi avamine tohutu põnevusega",
	"Midagi äärmiselt vürtsikat söömine (suu tuulutamine, vee otsimine)",
	"Maitses midagi vastikut ja püüdis seda mitte välja sülitada",
	"Joogi võtmine ja süljevõtmine (šokis välja pritsimine, ilma tegeliku veeta)",
	"Kõndimine nagu egiptlane (stiliseeritud õla- ja käeliigutused)",
	"Koomiline topeltvõtmine (pilk kõrvale, tagasi vaatamine, et üllatunult uuesti vaadata)",
	"Sõitmine konarlikul teel (istmel üles-alla tormamine)",
	"Kingituse raputamine, et arvata, mis on sees",
	"Kontrollimatu aevastuskriis",
	"Lipsu väga kiiresti sidumine (käed hägused)",
	"Kärbeste löömine, mis lihtsalt ei lähe ära (püsiv ärritus)",
	"Välgulöögi saamine (äkiline värin, rabatud ilme)",
	"Jalutuskäik vastu nähtamatut klaasist ust (järsk peatumine, nina hõõrumine)",
	"Sõitmine metsiku rulaga (istudes, vaikselt karjudes, käed püsti)",
	"Oma peegelpildi ees ehmatamine",
	"Liftinuppude meeletu vajutamine",
	"Hingeldamine ja kinnise ukse taga piilumine",
	"Tormamine ja võtmete otsimine taskus",
	"Kriipimine, et midagi kukkuvat kinni püüda",
	"Liigse reaktsiooni avaldamine maha läinud joogi peale, pühkides järsult oma särki",
	"Mimiline pingul haaramine viltuse ostukäru rattaga",
	"avalikult kinni jäänud tõmblukuga näpistamine",
	"Komistades ja seejärel šokeeritud näoga tasakaalu taastades",
	"Liialdatult kinni jäänud purgi kaane väänamine",
	"Meeletu otsimine nähtamatute kottide vahel",
	"Reageerimine kujuteldavale staatilisele elektrilöögile ukseklapist",
	"Teeskleb koputamist ja otsib meeleheitlikult kadunud võtmeid",
	"Vaadates ehmunult kujuteldavat maha läinud kohvi",
	"Nähtamatu kõrvaklappide kaabli lahti harutamist üle mängides",
	"Paaniliselt paanikas koperdamine pärast telefoni kukkumist",
	"Teesklemine, et oled läbimärg pärast ootamatut paduvihma",
	"Nähtamatu trossimine kangekaelse müügiautomaadiga",
	"Liialdatud üllatuse näitamine, kui lifti uks sulgub just õigel ajal",
	"Mimiline ärevil kontrollimine oma taskutes kadunud rahakoti järele",
	"Üle mängides kohmakat komistamist jäisel teel",
	"Nähtamatu kella korduva kontrollimise imiteerimine",
	"Ootamatu valju müra suhtes ootamatu šokiga reageerimine",
	"Ülepaisatud kohvri kiirustades sulgemise imiteerimine",
	"Kaootilise laadija kaabli lahti harutamisega seotud võitluse liialdamine",
	"Dramaatiliselt reageerides pisikesele, valusale paberilõikele",
	"Teeskleb, et peab aevastamist tagasi hoidma rahvarohkes ruumis",
	"Ettevaatlik vargsi astumine, et kedagi mitte äratada",
	"Paanikaga segatud liigne kergendus pärast seda, kui oled napilt kukkumist vältinud",
	"kujuteldava närimiskummi maha raputamine oma kingast",
	"Nähtamatute esemetega žongleerimise teesklemine, enne kui üks neist maha kukub",
	"Piinliku näo näitamine pärast riietusehäireid",
	"Kiire, meeletu tantsu imiteerimine, et vältida vastutulevat eset",
	"Paanikas telefonikõne ajal kujuteldava telefoniga vehklemine",
	"Üleliigne võitlus ülevoolava kraanikausiga",
	"Kiiresti libiseva lipsu sidumise imiteerimine",
	"Nähtamatute prillide reguleerimise teesklemine segaduses",
	"Imiteerib dramaatilist reaktsiooni metalluksest saadud löögile",
	"Liiga palju näitlejaid, kes püüavad kokku korjata laiali pillatud nähtamatuid pabereid",
	"Äkilise, liialdatud hüppe imiteerimine, kui ehmatab nähtamatu müra",
	"Teesklemine, et näpistab kangekaelset auto ust, mis ei taha avaneda",
	"Liigelda meeleheitlikult, et vabastada mudas kinni jäänud kinga",
	"Meeletu topeltkokkuvõtte imiteerimine, kui sa märkad, et su vöö on lahti",
	"Teesklemine, et tegeled vaikiva vaidlusega reageerimata objektiga",
	"Mimiline piinlik kähmlus, kui püüad vestlust lõpetada",
	"Üleliigse ärrituse üle näitlemine, kui kontrollid korduvalt kujuteldavat telefoni, et saada tekstisõnumit",
	"Mimiline närviline, kohkuv reaktsioon, kui sind ootamatult tabatakse",
	"Nähtamatu, valesti asetatud eseme üksikasjaliku otsimise teesklemine",
	"Paanika ja uskumatuse segu üle mängimine pärast ootamatut õnnetust",
	"Aeglustatud reaktsiooni matkimine, et õnnetust napilt vältida",
	"Nähtamatu raske koorma tasakaalustamise teesklemine, mis ootamatult ümber kallab",
	"Fedora vihma käes reguleerimine",
	"Nähtamatu sigareti süütamine",
	"Õnnetusjuhtumite kokkutulek",
	"Korvpalli vabavisked",
	"Jalgpalli karistuslöök",
	"Kaalutõstmise võitlus",
	"Kirja kirjutamine koju",
	"Sukeldumine",
	"Haavatud seltsimehe kandmine",
	"Langenud sõduri tervitamine",
	"Kummardus meistrile",
	"Põrgete harjutamine",
	"Mitme vastase blokeerimine",
	"Suletud rullilugemine",
	"Dramaatiline kiri kirjutamine",
	"Küünla süütamine pimedas saalis",
	"Hiiglasliku karu kallistamine",
	"Banaanikoore peal libistamine",
	"Jäätise jagamine lemmikloomaga",
	"Kummituse nägemine",
	"Hundi ulgumine",
	"Vastulause kohtus",
	"Tunnistajaga konsulteerimine",
	"Kohtuotsuse väljakuulutamine",
	"Eluliste tunnuste kontrollimine",
	"Tõsiste uudiste edastamine",
	"Taastusravi teostamine",
	"Varude otsimine",
	"Ukse tõkestamine",
	"Ettevaatlik lähenemine varemetes",
	"Paranoilised pilgud",
	"Power-Up poos",
	"Liialdatud reaktsioon",
	"Signatuurne rünnakuliigutus",
	"Pump-Action Shotgun'i laadimine",
	"Kiiret autojahti juhtides",
	"Vastutulest kõrvalehoidmine",
	"Ajastatud lõhkeaine paigaldamine",
	"Aardekaardi uurimine",
	"Trossisilla ületamine",
	"Vana templi püüniste vältimine",
	"Võidukas eseme avastamine",
	"Banaanikoorega libisemine",
	"Double Take",
	"Üle-topi naer",
	"Pasteet näkku",
	"Graafiku näitamine",
	"Eksperdi intervjueerimine",
	"Aeglane pisaravõitu konfrontatsioon",
	"Ärevust tekitav kokkuvarisemine",
	"Long Embrace Goodbye",
	"Loitsimine",
	"Mõõga tõmbamine kivist",
	"Riding a Dragon",
	"Peeniksi kutsumine",
	"Creeping Through a Haunted House",
	"Näriseva ukse avamine",
	"Põgenemine koletise eest",
	"Vaimu poolt vallutatud",
	"Suurendusklaasiga inspekteerimine",
	"Tap-Dance Break",
	"Kuriteopaiga kindlustamine",
	"Tõendite uurimine UV-valguses",
	"Peakorteri raadioside",
	"Sõrmejälgede tolmutamine",
	"Üleliigse ümberkujundamise paljastamine",
	"Dramaatiline löök",
	"Kokkuvarisemine šokeerivatest uudistest",
	"Pommi kahjutuks tegemine",
	"Enda ohverdamine",
	"Kõrgete keskpäevade duell",
	"Cowboy-mütsi kallutamine",
	"Lasso harjutamine",
	"Ratsutamine galopeeriva hobusega",
	"Laservõrgustiku ronimine",
	"Seifide lõhkumine",
	"Supi maitsmine ja maitseainete reguleerimine",
	"Köögiviljade tükeldamine suurel kiirusel",
	"Võltsitud isikut tõendava dokumendi näitamine",
	"Ukse juures salakuulamine",
	"Akende kinni panemine",
	"Aeglane zombi tassimine",
	"Close Call Bite",
	"Laskemoona otsimine",
	"Raha lugemine tagaruumis",
	"Powerful Handshake Deal",
	"Varjumine jälgimisdroonide eest",
	"Lasermõõgaga vehklemine",
	"Suurepäraste vuntside poleerimine",
	"Kepi koputamine ja mõtlemine",
	"Torusuitsu nuusutamine",
	"Päikesevarjuga kõndimine",
	"Hõbeda poleerimine teenijate ruumides",
	"Õhtusöögiks riietumine"
];