window.actionsData_en = [
    "Brushing your teeth",
    "Combing or brushing your hair",
    "Washing your face",
    "Taking a shower (washing your body)",
    "Drying off with a towel",
    "Getting dressed (putting on clothes)",
    "Tying your shoelaces",
    "Washing your hands",
    "Eating a meal (using a fork/spoon)",
    "Drinking from a cup",
    "Cooking on a stove (stirring a pot)",
    "Chopping vegetables on a cutting board",
    "Stirring soup in a pot",
    "Flipping pancakes in a pan",
    "Frying an egg in a pan",
    "Tasting food and adding a pinch of salt",
    "Washing dishes in the sink",
    "Drying dishes with a towel",
    "Vacuuming the floor",
    "Sweeping the floor with a broom (pantomime sweeping)",
    "Mopping the floor with a mop",
    "Dusting furniture with a cloth",
    "Wiping a window clean",
    "Taking out the trash (carrying a garbage bag)",
    "Folding laundry (folding clothes)",
    "Ironing clothes on an ironing board",
    "Making the bed (spreading sheets)",
    "Changing a light bulb overhead",
    "Setting the dining table",
    "Feeding a pet (pouring food into a bowl)",
    "Watering plants with a watering can",
    "Raking leaves in the yard",
    "Shoveling snow off a sidewalk",
    "Checking the mailbox for mail",
    "Locking or unlocking a door with a key",
    "Painting a wall with a paint roller",
    "Hammering a nail into a wall",
    "Sawing a piece of wood",
    "Tightening a screw with a screwdriver",
    "Climbing a set of stairs (stepping up)",
    "Reading a book or newspaper",
    "Writing a letter on paper",
    "Knitting with knitting needles",
    "Sewing a button onto fabric",
    "Searching for something under the couch",
    "Changing a baby’s diaper",
    "Pushing a baby stroller",
    "Walking a dog (holding a leash)",
    "Picking up toys from the floor",
    "Applying makeup in a mirror",
    "Shaving your face with a razor",
    "Putting on gloves",
    "Checking the time on a wristwatch",
    "Taking a photo with a smartphone",
    "Calling someone on the phone (holding phone to ear)",
    "Texting on a phone (typing with thumbs)",
    "Opening a stuck jar (struggling to twist the lid)",
    "Using scissors to cut paper",
    "Putting on socks",
    "Buttoning up a shirt",
    "Zipping up a jacket",
    "Pulling open a heavy/stuck door",
    "Pumping gas into a car at a gas station",
    "Paying with cash (handing over money)",
    "Swiping a credit card at a store",
    "Using an ATM machine",
    "Using a vending machine (pressing buttons, retrieving item)",
    "Drinking through a straw",
    "Slurping spaghetti noodles",
    "Chasing after a bus that’s leaving",
    "Watching TV (using a remote to change channels)",
    "Channel surfing (clicking remote repeatedly)",
    "Playing a board game (rolling dice, moving pieces)",
    "Signing a document (writing your signature)",
    "Using a hairdryer to dry hair",
    "Looking in a mirror and adjusting your hair or outfit",
    "Putting in contact lenses",
    "Painting your nails",
    "Hanging a picture frame on a wall (hammering nail)",
    "Playing with a yo-yo",
    "Blowing up a balloon",
    "Popping bubble wrap with your fingers",
    "Hula hooping around your waist",
    "Microwaving food and waiting for it to finish",
    "Tasting something from the fridge and gagging if it’s bad",
    "Tying a necktie around your collar",
    "Running/jogging at a steady pace",
    "Doing jumping jacks",
    "Doing push-ups",
    "Doing pull-ups (imagining a bar overhead)",
    "Lifting weights (bicep curls or lifting a barbell)",
    "Flexing your muscles like a bodybuilder",
    "Stretching in a yoga pose",
    "Doing an aerobics/dance exercise routine",
    "Skipping rope (jump rope)",
    "Riding a bicycle (pedaling and steering)",
    "Swimming (doing a swim stroke)",
    "Diving into a pool (arms overhead, jumping forward)",
    "Skiing downhill (bending knees, using poles)",
    "Ice skating (gliding and balancing with arms out)",
    "Roller skating or rollerblading",
    "Skateboarding (foot kicking and balancing on board)",
    "Surfing on a wave (balancing on an invisible surfboard)",
    "Snowboarding down a slope",
    "Rock climbing a wall (reaching and stepping upward)",
    "Hiking with a heavy backpack",
    "Playing soccer (dribbling and kicking an imaginary ball)",
    "Playing basketball (bouncing an imaginary ball, shooting)",
    "Swinging a baseball bat to hit a ball",
    "Pitching a baseball (winding up and throwing)",
    "Playing tennis (swinging a racket forehand/backhand)",
    "Serving a tennis ball (toss and swing)",
    "Playing volleyball (serving or spiking a ball)",
    "Swinging a golf club to hit a golf ball",
    "Bowling (rolling an invisible bowling ball)",
    "Playing ping pong (table tennis paddle swing)",
    "Throwing a football (American football quarterback throw)",
    "Catching a football pass",
    "Throwing a Frisbee disc",
    "Aiming a bow and shooting an arrow (archery)",
    "Boxing (sparring with fists, punching and guarding)",
    "Karate or martial arts moves (performing a kata or kicks)",
    "Fencing duel (sport sword fighting stance and thrust)",
    "Wrestling an opponent (grappling with air)",
    "Balancing on a balance beam (arms out for balance)",
    "Jumping on a trampoline (bouncing in place)",
    "Playing tug-of-war (pulling an invisible rope hard)",
    "Horseback riding (holding reins and bouncing in saddle)",
    "Riding a mechanical bull (rodeo style, one hand up)",
    "Fishing (casting a rod and reeling in)",
    "Running hurdles (sprinting and jumping an obstacle)",
    "Throwing a javelin",
    "Throwing a shot put (heaving with one shoulder)",
    "Doing a high jump (run and leap)",
    "Punching a boxing speed bag (rapid fists)",
    "Climbing a rope (hand-over-hand climbing motion)",
    "Sledding downhill (sitting and steering imaginary sled)",
    "Having a snowball fight (packing and throwing snowballs)",
    "Playing dodgeball (dodging and throwing a ball)",
    "Playing pool/billiards (lining up a pool cue and shooting)",
    "Rowing a boat (using oars in a rowing motion)",
    "Playing cricket (batting with a cricket bat)",
    "Playing ice hockey (handling a hockey stick and puck)",
    "Playing badminton (swinging a racket underhand to hit a shuttlecock)",
    "Doing a touchdown victory dance (football celebration)",
    "Performing a sumo wrestler’s stomp and stance",
    "Skydiving (free-falling and pulling a parachute ripcord)",
    "Scuba diving (swimming with hand fins and breathing through regulator)",
    "Whitewater rafting (paddling vigorously)",
    "Water skiing (holding a rope handle and balancing on skis)",
    "Sack racing (jumping forward with feet together as if in a sack)",
    "Playing a guitar (strumming and chording)",
    "Playing a piano (pressing keys with both hands)",
    "Playing a violin (bowing with one hand, fingering with the other)",
    "Playing drums (air drumming a drum set)",
    "Playing a flute (holding sideways and moving fingers)",
    "Playing a saxophone (fingering and blowing into sax)",
    "Playing a trumpet (buzzing into mouthpiece, pressing valves)",
    "Singing with a microphone (holding a mic and belting out)",
    "Dancing ballet (graceful spins and arm movements)",
    "Dancing hip-hop style (freestyle dance moves)",
    "Dancing a ballroom waltz (holding an invisible partner)",
    "Dancing disco (pointing fingers in the air, rhythmic steps)",
    "Tap dancing (quick tapping steps)",
    "Painting a picture on an easel (brushing on canvas)",
    "Drawing on paper (sketching with a pencil)",
    "Sculpting clay (molding clay with hands)",
    "Doing pottery on a potter’s wheel (shaping clay)",
    "Taking photographs with a camera (holding and clicking a camera)",
    "Filming with a video camera (shoulder camera, focusing)",
    "Acting on stage (performing a dramatic monologue or bowing to audience)",
    "Performing a magic trick (e.g., pulling an imaginary rabbit from a hat)",
    "Shuffling a deck of cards (bridge shuffle motion)",
    "Dealing playing cards out",
    "Playing chess (moving an invisible chess piece thoughtfully)",
    "Playing video games (focusing and pressing buttons on a controller)",
    "Knitting a scarf with knitting needles",
    "Using a sewing machine (pumping foot and guiding fabric)",
    "Calligraphy writing with a quill pen",
    "Arranging a bouquet of flowers",
    "Juggling balls (tossing and catching imaginary balls in rhythm)",
    "Juggling clubs or knives (imaginary juggling of dangerous objects)",
    "Walking a tightrope (arms out for balance, careful steps)",
    "Riding a unicycle (arms out, balancing while pedaling one wheel)",
    "Performing as a clown (miming a big smile, silly movements, maybe making a balloon animal)",
    "Mime stuck in an invisible box (classic mime routine, feeling the walls)",
    "Face painting (painting someone’s face with a brush – mimed)",
    "DJ mixing music (pretending to adjust turntables and bob head)",
    "Playing an air guitar (rocking out with no instrument)",
    "Conducting an orchestra (waving a conductor’s baton in time)",
    "Playing an accordion (pushing and pulling, pressing keys)",
    "Folding origami paper (intricately folding an invisible paper)",
    "Lassoing a rope (spinning an imaginary lasso overhead)",
    "Cartooning (drawing a cartoon character on paper)",
    "Performing a stand-up comedy act (delivering jokes with expressive gestures)",
    "Ventriloquism act (moving a dummy puppet’s mouth while 'silent')",
    "Solving a Rubik’s Cube (twisting an invisible cube quickly)",
    "Playing darts (aiming and throwing a dart, then reacting)",
    "Playing hopscotch (hopping through imaginary chalk squares)",
    "Driving a car (steering wheel, shifting gears)",
    "Driving a bus (big steering wheel, opening door lever)",
    "Driving a forklift (operating levers and careful driving)",
    "Flying an airplane (holding a yoke, flipping switches)",
    "Steering a ship (turning a large ship’s wheel)",
    "Digging with a shovel (scooping and tossing dirt)",
    "Hammering a nail (construction work)",
    "Sawing wood with a hand saw",
    "Drilling into a wall with a power drill",
    "Tightening a bolt with a wrench",
    "Operating a jackhammer (vibrating whole body)",
    "Welding metal (miming welding tool and protective visor)",
    "Plunging a toilet (using a plunger vigorously)",
    "Delivering mail (walking and putting mail in boxes)",
    "Milking a cow (sitting on stool, pulling imaginary udders)",
    "Chopping wood with an axe",
    "Driving a tractor on a farm",
    "Herding cattle (whistling and swinging an imaginary lasso)",
    "Typing on a keyboard (rapid finger movements)",
    "Writing on a clipboard or notepad",
    "Answering a phone call (office phone to ear)",
    "Filing documents in a filing cabinet",
    "Making photocopies (pressing copier button, waiting)",
    "Shredding papers in a shredder",
    "Giving a presentation (pointing at imaginary screen or chart)",
    "Mixing chemicals in beakers (scientist role)",
    "Looking through a microscope",
    "Investigating with a magnifying glass (detective role)",
    "Directing traffic (using hand signals to stop/go cars)",
    "Blowing a whistle (referee or police—silent blow, but gesture blowing and point)",
    "Handcuffing a suspect (holding wrists and clicking cuffs)",
    "Writing a parking ticket on a notepad",
    "Saluting (military salute)",
    "Marching in place (soldier drilling)",
    "Scanning someone with a metal detector wand (security guard)",
    "Spraying water from a fire hose (firefighter)",
    "Climbing a ladder (firefighter or worker climbing rungs)",
    "Carrying someone to safety over your shoulder (fireman’s carry with an imaginary person)",
    "Performing surgery (carefully using instruments on a patient)",
    "Listening to a heartbeat with a stethoscope (doctor exam)",
    "Giving an injection with a syringe (nurse or doctor)",
    "Checking a patient’s temperature (thermometer under tongue)",
    "Putting on surgical gloves and mask (snap gloves)",
    "Taking someone’s blood pressure (wrapping cuff, squeezing pump)",
    "Driving an ambulance (sirens wailing motion)",
    "Pulling the whistle cord on a train (locomotive engineer)",
    "Punching tickets on a train (train conductor)",
    "Bartending (shaking a cocktail shaker, pouring into glass)",
    "Pouring a drink from a bottle into a glass",
    "Serving food on a tray (waiter balancing trays)",
    "Stir-frying in a wok (chef tossing food in pan)",
    "Tossing pizza dough in the air (pizzeria chef)",
    "Tasting soup as a chef (sip and approve or add salt)",
    "Cutting hair with scissors and comb (hairdresser)",
    "Using a leaf blower in a yard (gardener)",
    "Mowing the lawn with a push mower",
    "Cutting down a tree with a two-handed saw or axe",
    "Taking photographs at an event (professional photographer with camera)",
    "Giving a speech or lecture (politician or professor gesturing)",
    "Banging a gavel (judge in a courtroom)",
    "Demonstrating safety instructions on an airplane (flight attendant miming seatbelt, oxygen mask)",
    "Floating in zero-gravity as an astronaut (slow movements, tethering self)",
    "Pulling a tooth (dentist wiggling and yanking an invisible tooth, showing it)",
    "Examining a pet (veterinarian checking a dog or cat)",
    "Shelving books (librarian placing books on a high shelf)",
    "Scanning items at a checkout (cashier beeping items)",
    "Using a security wand at airport security (scanning a person)",
    "Working on an assembly line (repeating a task quickly on an imaginary conveyor)",
    "Taking a selfie video for social media (influencer posing with phone)",
    "Exterminating bugs (spraying insecticide in corners with a tank sprayer)",
    "Communicating in sign language (gesturing as if using ASL)",
    "Packing a box for shipping (taping up a cardboard box)",
    "Performing CPR on a dummy (chest compressions on an invisible person)",
    "Counting money (bank teller flipping through bills)",
    "Giving someone a big hug",
    "Fanning yourself because it’s hot",
    "Coughing into your hand or elbow",
    "Hiccuping (jerking shoulders)",
    "Whistling casually (puckering lips, though no sound)",
    "Staring off daydreaming (head in clouds expression)",
    "Sleepwalking with arms outstretched",
    "Giving someone a piggyback ride (carrying an imaginary person on back)",
    "Snapping your fingers to music or in appreciation",
    "Flapping your arms and clucking like a chicken",
    "Flying like a bird (flapping wings and soaring)",
    "Panting and begging like a dog (tongue out, paws up)",
    "Stretching and preening like a cat (licking paw, arching back)",
    "Galloping like a horse (clapping hands to mimic hooves, neigh silently)",
    "Sniffing and oinking like a pig (snout impression)",
    "Buzzing and flying like a bee (using finger as a stinger)",
    "Fluttering like a butterfly (gentle wing motions)",
    "Crowing like a rooster at dawn (hands as beak)",
    "Leaping out of water like a dolphin",
    "Clapping and barking like a seal (flapping hands together)",
    "Stomping with heavy steps and tiny arms like a T-Rex dinosaur",
    "Trapped in an box (feeling the walls around you)",
    "Pulling an rope (tug-of-war against an unseen force)",
    "Climbing an ladder (reaching up and stepping)",
    "Leaning on an wall (miming a wall for comedic effect)",
    "Walking against a strong wind (pushing forward, body at angle)",
    "Walking on hot coals (tiptoeing quickly, shaking foot in pain)",
    "Slipping on a banana peel (big comedic fall recovery)",
    "Stepping on something sharp (jumping up and hopping in pain)",
    "Carrying a very heavy object (staggering under weight, straining)",
    "Lifting an extremely heavy weight (strongman attempt, shaking arms)",
    "Trying to lift something too heavy and dropping it suddenly",
    "Picking up something that turns out to be very light (overpull and stumble)",
    "Being yanked forward by a big dog on a leash",
    "Chasing your own tail (spinning in circles playfully)",
    "Getting your finger caught in a door (yanking hand back, shaking it)",
    "Swatting at a bee buzzing around you frantically",
    "Walking on a tightrope high up (arms out, teetering carefully)",
    "Balancing a book on your head while walking",
    "Juggling balls (tossing and catching with no props)",
    "Riding a magic carpet (sitting, steering imaginary carpet)",
    "Flying on a broomstick (as if you’re a witch/wizard flying)",
    "Using a jetpack (strapping on and blasting off, unsteady hover)",
    "Doing the moonwalk dance (gliding backward smoothly)",
    "Running in slow motion (exaggerated slow running and face)",
    "Moving in reverse as if a video is rewinding",
    "Acting like a puppet on strings (jerky, controlled movements from above)",
    "Getting electrocuted comically (shaking and hair standing up)",
    "Blowing up a balloon until it pops (big sudden surprise reaction)",
    "Pretending to shrink down to tiny size (crouching lower, looking up)",
    "Pretending to grow giant (reaching up high, stepping heavy)",
    "Walking through thick jelly or mud (exaggerated resistance in movement)",
    "Defusing a time bomb (carefully clipping wires, tense expressions)",
    "Playing tug-of-war alone (pulling an unseen rope, then being pulled forward)",
    "Floating in zero gravity (slow, drifting movements)",
    "Fighting in slow motion (throwing punches and dodging slowly)",
    "Performing a dramatic faint (hand on forehead, slow collapse)",
    "Opening an imaginary gift box with huge excitement",
    "Eating something extremely spicy (fanning mouth, searching for water)",
    "Tasting something disgusting and trying not to spit it out",
    "Taking a drink and doing a spit-take (spraying out in shock, without actual water)",
    "Walking like an Egyptian (stylized shoulder and arm moves)",
    "Doing a comical double-take (look away, snap back to look again in surprise)",
    "Driving on a bumpy road (jostling up and down in a seat)",
    "Shaking a present to guess what’s inside",
    "Having an uncontrollable sneezing fit",
    "Tying a tie very quickly (hands a blur)",
    "Swatting at flies that just won’t go away (persistent annoyance)",
    "Getting struck by lightning (a sudden jolt, frazzled look)",
    "Walking into an invisible glass door (stop abruptly, rub nose)",
    "Riding a wild rollercoaster (sitting, screaming silently, hands up)",
    "Getting scared by your own reflection in a mirror",
    "Frantically pressing elevator buttons",
    "Gasping and peeking around a closed door",
    "Rushing and fumbling for keys in your pocket",
    "Scrambling to catch something falling",
    "Overreacting to a spilled drink by dramatically wiping your shirt",
    "Miming a tight grip on a wonky shopping cart wheel",
    "Fumbling with a jammed zipper in public",
    "Stumbling and then regaining your balance with a shocked expression",
    "Exaggeratedly twisting a stuck jar lid",
    "Miming a frantic search through invisible bags",
    "Reacting to an imaginary static shock from a doorknob",
    "Pretending to knock and search desperately for lost keys",
    "Gazing in dismay at an imaginary spilled coffee",
    "Overacting the struggle of untangling an invisible headphone cable",
    "Miming a panicked scramble after dropping a phone",
    "Pretending to be drenched after an unexpected downpour",
    "Engaging in an invisible tug-of-war with a stubborn vending machine",
    "Showing exaggerated surprise as an elevator door closes just in time",
    "Miming a frantic check through your pockets for a missing wallet",
    "Overacting a clumsy stumble on an icy patch",
    "Miming the action of repeatedly checking an invisible watch",
    "Reacting with sudden shock to an unexpected loud noise",
    "Miming the hurried closing of an overstuffed briefcase",
    "Exaggerating the struggle of untangling a chaotic charger cable",
    "Dramatically reacting to a tiny, painful paper cut",
    "Pretending to hold back a sneeze in a crowded room",
    "Miming a cautious tiptoe to avoid waking someone",
    "Overacting relief mixed with panic after narrowly avoiding a fall",
    "Shaking off an imaginary piece of gum from your shoe",
    "Pretending to juggle invisible items before one drops",
    "Flashing an embarrassed face after a wardrobe malfunction",
    "Miming a quick, frantic dance to dodge an oncoming object",
    "Fumbling with an imaginary phone during a panicked call",
    "Overacting a frustrated struggle with an overflowing sink",
    "Miming the action of hurriedly tying a tie that keeps slipping",
    "Pretending to adjust an invisible pair of glasses in confusion",
    "Miming a dramatic reaction to receiving a shock from a metal door",
    "Overacting the scramble to pick up scattered invisible papers",
    "Miming a sudden, exaggerated leap when startled by an unseen noise",
    "Pretending to fumble with a stubborn car door that won’t open",
    "Overacting a desperate tug to free a shoe stuck in mud",
    "Miming a frantic double-take when you realize your fly is unzipped",
    "Pretending to engage in a silent argument with an unresponsive object",
    "Miming the awkward shuffle when you’re trying to end a conversation",
    "Overacting the exasperation of repeatedly checking an imaginary phone for a text",
    "Miming a nervous, stuttering reaction when caught off guard",
    "Pretending to mime a detailed search for an invisible misplaced object",
    "Overacting a mix of panic and disbelief after an unexpected mishap",
    "Miming a slow-motion reaction to narrowly avoid an accident",
    "Pretending to balance an invisible heavy load that suddenly tips over",
    "Adjusting a Fedora in the Rain",
    "Lighting an Invisible Cigarette",
    "Accidental Spill Meet-Cute",
    "Basketball Free Throw",
    "Soccer Penalty Kick",
    "Weightlifting Struggle",
    "Writing a Letter Home",
    "Diving for Cover",
    "Carrying a Wounded Comrade",
    "Saluting Fallen Soldier",
    "Bow to the Master",
    "Practicing Kicks",
    "Blocking Multiple Opponents",
    "Reading a Sealed Scroll",
    "Dramatic Quill Writing",
    "Lighting a Candle in a Dark Hall",
    "Hugging a Giant Teddy Bear",
    "Slipping on a Banana Peel",
    "Sharing Ice Cream with a Pet",
    "Seeing a Ghost",
    "Werewolf Howl",
    "Objecting in Court",
    "Consulting a Witness",
    "Verdict Announcement",
    "Checking Vital Signs",
    "Delivering Serious News",
    "Performing CPR",
    "Scavenging for Supplies",
    "Barricading a Door",
    "Cautious Approach in Ruins",
    "Paranoid Glances",
    "Power-Up Pose",
    "Exaggerated Reaction",
    "Signature Attack Move",
    "Loading a Pump-Action Shotgun",
    "High-Speed Car Chase Steering",
    "Dodging Incoming Fire",
    "Planting a Timed Explosive",
    "Studying a Treasure Map",
    "Crossing a Rickety Rope Bridge",
    "Dodging Ancient Temple Traps",
    "Triumphant Artifact Discovery",
    "Banana Peel Slip",
    "Double Take",
    "Over-the-Top Laugh",
    "Pie in the Face",
    "Showing a Graph",
    "Interviewing an Expert",
    "Slow Tearful Confrontation",
    "Anguished Collapse",
    "Long Embrace Goodbye",
    "Casting a Spell",
    "Drawing a Sword from a Stone",
    "Riding a Dragon",
    "Summoning a Phoenix",
    "Creeping Through a Haunted House",
    "Opening a Creaky Door",
    "Fleeing a Monster",
    "Possessed by a Spirit",
    "Magnifying Glass Inspection",
    "Tap-Dance Break",
    "Securing a Crime Scene",
    "Examining Evidence Under UV Light",
    "Radioing Headquarters",
    "Fingerprint Dusting",
    "Over-the-Top Makeover Reveal",
    "Dramatic Slap",
    "Collapsing from Shocking News",
    "Disabling a Bomb",
    "Sacrificing Yourself",
    "High-Noon Duel",
    "Tipping Cowboy Hat",
    "Lasso Practice",
    "Riding a Galloping Horse",
    "Laser Grid Crawl",
    "Cracking a Safe",
    "Tasting Soup and Adjusting Seasoning",
    "Chopping Vegetables at High Speed",
    "Flashing a Fake ID",
    "Eavesdropping at a Door",
    "Boarding Up Windows",
    "Slow Zombie Shuffle",
    "Close Call Bite",
    "Scrounging for Ammo",
    "Counting Money in a Back Room",
    "Powerful Handshake Deal",
    "Hiding from Surveillance Drone",
    "Wielding a Laser Sword",
    "Polishing a Magnificent Mustache",
    "Tapping a Cane and Thinking",
    "Taking a Sniff of Pipe Smoke",
    "Walking with a Parasol",
    "Polishing Silver in the Servants’ Quarters",
    "Dressing for Dinner"
];