window.actionsData_et = [
    // Igapäevased tegevused
    "Hammaste pesemine",
    "Juuste kammimine või harjamine",
    "Näo pesemine",
    "Duši all käimine (keha pesemine)",
    "Rätikuga kuivatamine",
    "Riietumine (riiete selga panemine)",
    "Kingapaelte sidumine",
    "Käte pesemine",
    "Söömine (kahvli/lusikaga)",
    "Tassist joomine",
    "Pliidil kokkamine (poti segamine)",
    "Köögiviljade hakkimine lõikelaual",
    "Supi segamine potis",
    "Pannkookide keeramine pannil",
    "Muna praadimine pannil",
    "Toidu maitsmine ja näpuotsatäie soola lisamine",
    "Nõude pesemine kraanikausis",
    "Nõude kuivatamine rätikuga",
    "Põranda tolmuimemine",
    "Põranda pühkimine harjaga",
    "Põranda mopimine",
    "Mööbli tolmu pühkimine lapiga",
    "Akna puhastamine",
    "Prügi väljaviimine (prügikoti kandmine)",
    "Pesu voltimine",
    "Riiete triikimine triikrauaga",
    "Voodi korrastamine (voodipesu laotamine)",
    "Lambipirnide vahetamine",
    "Söögilaua katmine",
    "Lemmiklooma toitmine (toidu kaussi kalamine)",
    "Taimede kastmine kastekannuga",
    "Lehtede riisumine õues",
    "Lume rookimine kõnniteelt",
    "Postkastist kirjade kontrollimine",
    "Ukse lukustamine või avamine võtmega",
    "Seina värvimine värvirulliga",
    "Naela seina löömine",
    "Puutüki saagimine",
    "Kruvi keeramine kruvikeerajaga",
    "Trepist üles minemine",
    "Raamatu või ajalehe lugemine",
    "Kirja kirjutamine paberile",
    "Kudumine kudumisvarrastega",
    "Nööbi õmblemine riidele",
    "Millegi otsimine diivani alt",
    "Beebi mähkme vahetamine",
    "Lapsevanker lükkamine",
    "Koeraga jalutamine (rihma hoidmine)",
    "Mänguasjade põrandalt korjamine",
    "Meigi pealekandmine peegli ees",
    "Näo raseerimine",
    "Kinnaste kätte panemine",
    "Kellaaja kontrollimine käekellalt",
    "Nutitelefoniga pildistamine",
    "Helistamine (telefoni kõrva ääres hoidmine)",
    "Telefonil sõnumite kirjutamine",
    "Kinnise purgi avamine (kaane keeramine)",
    "Kääridega paberi lõikamine",
    "Sokkide jalga panemine",
    "Särgi nööpide kinni panemine",
    "Jaki lukku tõmbamine",
    "Raske ukse avamine",
    "Auto tankimine bensiinijaamas",
    "Sularahaga maksmine",
    "Krediitkaardiga maksmine poes",
    "Pangaautomaadi kasutamine",
    "Müügiautomaadi kasutamine",
    "Kõrrega joomine",
    "Spagetite sörpimine",
    "Lahkuva bussi järele jooksmine",
    "Teleri vaatamine (puldi kasutamine)",
    "Kanalite vahetamine (puldi klõpsutamine)",
    "Lauamängu mängimine (täringute veeretamine)",
    "Dokumendi allkirjastamine",
    "Fööni kasutamine juuste kuivatamiseks",
    "Peeglisse vaatamine ja soengu sättimine",
    "Kontaktläätsede silma panemine",
    "Küünte lakkimine",
    "Pildi raami seinale riputamine",
    "Jojoga mängimine",
    "Õhupalli täis puhumine",
    "Mullikile lõhkumine sõrmedega",
    "Hularõngaga keerutamine",
    "Toidu soojendamine mikrolaineahjus",
    "Külmikust millegi maitsmine ja öökimine kui on halb",
    "Lipsu sidumine kaela ümber",
    "Jooksmine/sörkimine ühtlases tempos",
    "Hüplemisharjutuste tegemine",
    "Kätekõverduste tegemine",
    "Lõuatõmmete tegemine",
    "Raskuste tõstmine",
    "Lihaste painutamine nagu kulturist",
    "Jooga asendi tegemine",
    "Aeroobika/tantsuline treening",
    "Hüppenööriga hüppamine",
    "Jalgrattaga sõitmine",
    "Ujumine",
    "Basseini sukeldumine",
    "Mäesuusatamine",
    "Uisutamine",
    "Rulluisutamine",
    "Rulaga sõitmine",
    "Surfamine lainel",
    "Lumelauaga sõitmine",
    "Seinal ronimine",
    "Raske seljakotiga matkamine",
    "Jalgpalli mängimine",
    "Korvpalli mängimine",
    "Pesapalli kurikaga löömine",
    "Pesapalli viskamine",
    "Tennise mängimine",
    "Tennisepalli servimine",
    "Võrkpalli mängimine",
    "Golfi mängimine",
    "Keeglimäng",
    "Lauatennise mängimine",
    "Ameerika jalgpalli viskamine",
    "Ameerika jalgpalli püüdmine",
    "Lendava taldriku viskamine",
    "Vibuga laskmine",
    "Poksimine",
    "Karate või võitluskunstide liigutused",
    "Vehklemine",
    "Maadlemine",
    "Poomil tasakaalu hoidmine",
    "Batuudil hüppamine",
    "Köievedu",
    "Ratsutamine",
    "Mehaanilise pulliga ratsutamine",
    "Kalastamine",
    "Tõkkejooks",
    "Odavise",
    "Kuulitõuge",
    "Kõrgushüpe",
    "Poksikoti löömine",
    "Köiel ronimine",
    "Kelgutamine",
    "Lumesõda",
    "Rahvastepalli mängimine",
    "Piljardi mängimine",
    "Paadiga sõudmine",
    "Kriketi mängimine",
    "Jäähoki mängimine",
    "Sulgpalli mängimine",
    "Touchdown'i võidutants",
    "Sumomaadleja samm ja asend",
    "Langevarjuga hüppamine",
    "Sukelduma",
    "Kärestikul sõitmine",
    "Veesuusatamine",
    "Kotijooks",
    "Kitarri mängimine",
    "Klaveri mängimine",
    "Viiuli mängimine",
    "Trummide mängimine",
    "Flöödi mängimine",
    "Saksofoni mängimine",
    "Trompeti mängimine",
    "Ooperi laulmine",
    "Mikrofoniga laulmine",
    "Ballett",
    "Hip-hop tants",
    "Valsi tantsimine",
    "Disko tantsimine",
    "Stepptants",
    "Breiktants",
    "Molbertil maalimine",
    "Paberile joonistamine",
    "Savi voolimine",
    "Potikedral töötamine",
    "Fotode tegemine",
    "Videoga filmimine",
    "Laval näitlemine",
    "Mustkunsti triki tegemine",
    "Kaartide segamine",
    "Kaartide jagamine",
    "Male mängimine",
    "Videomängude mängimine",
    "Salli kudumine",
    "Õmblusmasina kasutamine",
    "Kalligraafia kirjutamine",
    "Lillekimbu seadmine",
    "Pallidega žongleerimine",
    "Kurikate või nugadega žongleerimine",
    "Köiel kõndimine",
    "Üherattalisel sõitmine",
    "Klounina esinemine",
    "Miimi etendus nähtamatus kastis",
    "Näomaalingute tegemine",
    "DJ-na muusika miksimine",
    "Õhukitarri mängimine",
    "Orkestri juhtimine",
    "Akordioni mängimine",
    "Origami voltimine",
    "Lassoga püüdmine",
    "Karikatuuride joonistamine",
    "Stand-up koomikuna esinemine",
    "Kõhurääkija etendus",
    "Rubiku kuubiku lahendamine",
    "Nooleviskes",
    "Keksumäng",
    "Auto juhtimine",
    "Bussi juhtimine",
    "Tõstuki juhtimine",
    "Lennuki juhtimine",
    "Laeva juhtimine",
    "Labidaga kaevamine",
    "Haamriga naela löömine",
    "Puidu saagimine",
    "Seina puurimine",
    "Mutrivõtmega keerama",
    "Suruõhuvasaraga töötamine",
    "Keevitamine",
    "Tualetipoti pumpamine",
    "Posti kandmine",
    "Lehma lüpsmine",
    "Puude lõhkumine",
    "Traktori juhtimine",
    "Karjakasvatamine",
    "Klaviatuuril trükkimine",
    "Kirjutamine",
    "Telefonikõnele vastamine",
    "Dokumentide failimine",
    "Koopiate tegemine",
    "Paberite purustamine",
    "Presentatsiooni pidamine",
    "Kemikaalide segamine",
    "Mikroskoobi kasutamine",
    "Luubiga uurimine",
    "Liikluse suunamine",
    "Vile puhumine",
    "Käeraudade panemine",
    "Parkimistrahvi kirjutamine",
    "Sõjaväeline tervitus",
    "Marssimine",
    "Metallidetektoriga kontrollimine",
    "Tuletõrjevoolikuga pritsimine",
    "Redelil ronimine",
    "Kannatanu päästmine",
    "Operatsiooni tegemine",
    "Südame kuulamine",
    "Süsti tegemine",
    "Palaviku mõõtmine",
    "Kirurgiliste kinnaste panemine",
    "Vererõhu mõõtmine",
    "Kiirabi juhtimine",
    "Rongi vile tõmbamine",
    "Piletite kontrollimine",
    "Kokteili segamine",
    "Joogi valamine",
    "Toidu serveerimine",
    "Vokkpannil praadimine",
    "Pitsa taigna viskamine",
    "Supi maitsmine",
    "Juuste lõikamine",
    "Lehtede puhumine",
    "Muru niitmine",
    "Puu langetamine",
    "Sündmusel pildistamine",
    "Kõne pidamine",
    "Kohtuhaamri löömine",
    "Lennuki ohutusjuhiste demonstreerimine",
    "Kosmoses hõljumine",
    "Hamba välja tõmbamine",
    "Lemmiklooma uurimine",
    "Raamatute riiulisse panemine",
    "Kassas toodete skaneerimine",
    "Turvakontroll",
    "Konveieriliinil töötamine",
    "Sotsiaalmeedia selfivideo tegemine",
    "Kohtus kaitsekõne pidamine",
    "Putukate tõrjumine",
    "Viipekeeles suhtlemine",
    "Paki pakkimine",
    "Elustamine",
    "Raha lugemine",
    "Tervituseks lehvitamine",
    "Hüvastijätuks lehvitamine",
    "Käe surumine",
    "Kallistamine",
    "Pöidla ülesse näitamine",
    "Pöidla alla näitamine",
    "Plaksutamine",
    "High-five tegemine",
    "Rusikate kokku löömine",
    "Kaugele osutamine",
    "Kellegi kutsumine",
    "Õlgade kehitamine",
    "Noogutamine",
    "Pea raputamine",
    "Otsmikule plaksutamine",
    "Käte rinnale ristamine",
    "Kannatamatult jala koputamine",
    "Vaikuse palumise žest",
    "Kõrvade katmine",
    "Silmade katmine",
    "Suu katmine üllatusest",
    "Silmade pööritamine",
    "Palvetamine",
    "Viisakas kummardamine",
    "Sõjaväeline tervitus",
    "Palvetamine (käed koos, silmad suletud)",
    "Viisakalt või austusega kummardamine",
    "Sõjaväeline tervitus",
    "Õhusuudluse saatmine",
    "Põsemusiga tervitamine (õhusuudlus)",
    "Sõrmega eitavalt viibutamine ('ei-ei' žest)",
    "Käed puusas seismine (kannatamatu või karm hoiak)",
    "Vihaselt jalaga trampimine",
    "Rõõmust hüppamine (põnevusest üles hüppamine)",
    "Võidurõõmus rusikaga vehkimine ('Jess!')",
    "Pisarate pühkimine nutmise ajal",
    "Südamest naermine (kõhtu hoides, vaikne naer)",
    "Naerust kõveras olema",
    "Külmast värisema (käsi hõõruma, hammaste lõgisemine)",
    "Kuumuse tõttu end lehvitama",
    "Kätte või küünarnukki köhima",
    "Aevastamine (aehhuu liigutus)",
    "Uniselt haigutamine",
    "Luksuma (õlgade tõmblemine)",
    "Vaikselt vilistamine (huulte torusse ajamine, ilma helita)",
    "Unistades kaugusesse vaatamine (pea pilvedes ilme)",
    "Väljasirutatud kätega unes kõndimine",
    "Metsikul Ameerika mäel sõitma (istudes, vaikselt karjudes, käed üleval)",
    "Oma peegelpildist ehmatama",
    "editeerimine (risti jalgadega istumine, rahulikult suletud silmad)",
    "Peopesade kokkupanek ja kummardamine (namaste tervitus)",
    "Nina nokkimine (diskreetselt või koomiliselt)",
    "Segaduses pead kratsima",
    "Kellelegi kukil sõitu pakkumine (kujuteldava inimese seljas kandmine)",
    "Üksi kivi-paber-käärid mängimine (rusika ja lameda käe žestid)",
    "Käe tõstmine 'stopp' märguandeks",
    "Sõrmedega muusika või tunnustuse märgiks plaksutamine",
    "Džässikäte viibutamine (sädelevate sõrmede lehvitamine)",
    "Kätelaine tegemine (nagu staadionil)",
    "Õhus allkirja andmine (autogrammi märkimiseks)",
    "Meeleheites käte üles viskamine",
    "Alistumiseks käte üles tõstmine",
    "Õnneks sõrmede ristamine",
    "Närviliselt küünte närimine",
    "Ärevalt edasi-tagasi kõndimine",
    "Vihas rusikate pigistamine ja värisema (raevu vaoshoidmine)",
    "Sõrmedega 'õhutsitaate' tegemine",
    "Skeptiliselt ühe kulmu tõstmine",
    "Hämmastunud žesti tegemine (käed peast eemale plahvatamas)",
    "Sarkastiliselt aeglaselt plaksutamine",
    "Tiibadega vehkimine ja kaagutamine nagu kana",
    "Linnuna lendamine (tiibade lehvitamine ja õhus liuglemine)",
    "Elevandi matkimine (käsi londina, vaikne pasundamine)",
    "Ahvi matkimine (sügamine, banaani söömine, kiikumine)",
    "Känguruna hüppamine (väikesed hüpped, käed väikeste käppadena)",
    "Konnana hüppamine (kükitamine ja üles hüppamine)",
    "Maduna roomamine (käe või keha looklev liigutus, vaikne sisimine)",
    "Koera moodi lõõtsutamine ja anuma (keel väljas, käpad üleval)",
    "Kassina sirutamine ja end korrastamine (käpa lakkumine, selja kumeraks ajamine)",
    "Kalana ujumine (käed koos, keha looklev)",
    "Pingviinina tippamine (käed külgedel, väikesed sammud)",
    "Nina tõmblemine ja jänesena hüppamine",
    "Hobusena galopeerimne (käte plaksutamine kabjade matkimiseks, vaikne hirnumine)",
    "Pullina maad kraapima ja ründama valmistumine",
    "Seana nuuskima ja röhkima (kärsa matkimine)",
    "Mesilasena sumisema ja lendama (sõrme astlana kasutamine)",
    "Liblikana lehvima (õrnad tiivalöögid)",
    "Pardina taaruma ja prääksuma",
    "Kukekirena koidikul (käed nokana)",
    "Delfiinina veest välja hüppamine",
    "Haina tiirutamine (seljauim käena pea kohal)",
    "Karuna möirgama ja käppadega vehkima",
    "Lõvina möirgama (vaikne möire, käpad üleval)",
    "Tiigrina džunglis hiilima",
    "Sääsena sumisema ja hammustada püüdma",
    "Gorillana rinda taguma",
    "Kaheksajala kombitsatena käsi lehvitama",
    "Krabina külgsuunas liikuma (käed sõrgadena)",
    "Hiirena piiksuma ja näksima",
    "Öökullina pead pöörama ja huikama",
    "Hundina kuu poole uluma",
    "Teona aeglaselt liikuma (roomamine, üks käsi kojana)",
    "Kotkana liuglema (käed laiali sirutatud)",
    "Kilpkonnana aeglaselt roomama raske kilbiga",
    "Kalkunina korisema ja uhkeldavalt kõndima",
    "Nahkhiirena pea alaspidi rippuma ja tiibu lehvitama",
    "Kassina karvapallikest välja köhima",
    "Kassile vanni andmine (kujuteldava märja kassiga võitlemine)",
    "Zombina taaruma (käed ees, lohisev kõnnak)",
    "Robotina nõksutama (jäigad käed ja jalad)",
    "Vaimuna hõljuma ja 'Buu!' tegema (käte lehvitamine, õudne hoiak)",
    "Vampiirina teesklemine (keep näo ees, kihvade näitamine)",
    "Superkangelase lennuasendi võtmine (üks käsi ette sirutatud)",
    "Superkangelasena maandumine (põlvili, rusikas maas)",
    "Neljakäpukil beebina roomama",
    "Vanainimesena kepiga komberdama",
    "Kitsena puksima",
    "Eeslina tagajalgadega lööma (tagasilöögi liigutus)",
    "Hüäänina itsitama (vaikne naer metsiku värinaga)",
    "Flamingona ühel jalal seisma",
    "Lehmana mäletsema (aeglane mälumine, tühi pilk)",
    "Paabulinnuna kujuteldavat saba lehvitama ja uhkeldama",
    "Vaksikuna liikuma (sõrmega mööda kätt roomama)",
    "Laiskloomana aeglaselt liikuma",
    "Hülgena plaksutama ja haukuma (käsi kokku lööma)",
    "T-Rex dinosauruse moodi raskete sammudega käima ja väikeste kätega vehkima",
    "Nähtamatus kastis lõksus olema (seinu kombates)",
    "Nähtamatut köit tõmbama (nähtamatu jõuga köieveos)",
    "Nähtamatut redelit ronima (üles küünitamine ja astumine)",
    "Nähtamatule seinale najatuma (koomilise efekti jaoks seina matkima)",
    "Tugeva tuule vastu kõndima (edasi suruma, keha nurga all)",
    "Kuumadel sütel kõndima (kiirelt kikivarvul, jalga valu pärast raputama)",
    "Banaanikoore peal libisema (suur koomiline kukkumine ja taastumine)",
    "Millelegi teravale astuma (üles hüppama ja valust hüplema)",
    "Väga rasket eset kandma (raskuse all vaaruma, pingutama)",
    "Äärmiselt rasket raskust tõstma (tugevusmehe katse, värisevad käed)",
    "Püüdes midagi liiga rasket tõsta ja äkki maha pillama",
    "Midagi tõstes avastama, et see on väga kerge (üle tõmbama ja komistama)",
    "Suure koera poolt rihma otsas edasi tõmmatama",
    "Oma saba taga ajama (mänguliselt ringi keerlema)",
    "Sõrme ukse vahele jätma (kätt tagasi tõmbama, raputama)",
    "Paaniliselt ümber lendavat mesilast eemale peletama",
    "Avastama nätsu kinga all (jalga tõstma, tõmbama)",
    "Kõrgel köiel kõndima (käed laiali, ettevaatlikult tasakaalustama)",
    "Kõndides raamatut pea peal tasakaalustama",
    "Nähtamatuid palle žongleerima (viskama ja püüdma ilma vahenditeta)",
    "Võluvaiba ratsutamine (istumine, kujuteldava vaiba juhtimine)",
    "Luuavarrel lendamine (nagu nõid/võlur lennates)",
    "Reaktiivseljakotti kasutama (selga panema ja õhku tõusma, ebastabiilne hõljumine)",
    "Kuukõndi tegema (sujuvalt tagurpidi libisema)",
    "Aegluubis jooksma (liialdatud aeglane jooks ja näoilme)",
    "Tagurpidi liikuma nagu videot tagasi kerides",
    "Nööridega nukuna liikuma (tõmblev, ülalt juhitud liikumine)",
    "Koomiliselt elektrilööki saama (värisema ja juuksed püsti)",
    "Õhupalli täis puhuma kuni see plahvatab (suur ootamatu reaktsioon)",
    "Teesklema väikseks kahanemist (kükitama, üles vaatama)",
    "Teesklema hiiglaseks kasvamist (üles sirutama, raskelt astuma)",
    "Paksu tarretise või muda sees kõndima (liialdatud vastupanu liikumises)",
    "Ajapommi kahjutuks tegema (ettevaatlikult juhtmeid lõikama, pingelised ilmed)",
    "Üksinda köieveos olema (nähtamatut köit tõmbama, siis ette kukkuma)",
    "Nullgravitatsioonil hõljuma (aeglased, triivivad liigutused)",
    "Aegluubis võitlema (aeglaselt lööke andma ja vältima)",
    "Dramaatiliselt minestama (käsi laubal, aeglane kokku vajumine)",
    "Kujuteldavat kingitust suure põnevusega avama",
    "Midagi äärmiselt tulise sööma (suud lehvitama, vett otsima)",
    "Midagi vastikut maitsma ja püüdma mitte välja sülitada",
    "Jooki võtma ja üllatusest pritsima (šokist välja prskama, ilma päris veeta)",
    "Egiptlase moodi kõndima (stiliseeritud õla ja käe liigutused)",
    "Koomilist topeltpilku tegema (ära vaatama, üllatusega uuesti vaatama)",
    "Künklikul teel sõitma (istmel üles-alla põrkuma)",
    "Kingitust raputama, et aimata mis sees on",
    "Kontrollimatu aevastushoog",
    "Väga kiiresti lipsu siduma (käed häguseks liikumas)",
    "Tüütuid kärbseid ära ajama (püsiv tüütus)",
    "Välgu tabamust saama (äkiline võpatus, sassis välimus)",
    "Nähtamatu klaasukse vastu kõndima (järsult peatuma, nina hõõruma)",
    "Metsikul ameerika mäel sõitmine (istudes, vaikselt karjudes, käed üleval)",
    "Oma peegelpildist kohkumine",
    "Lifti nuppude paaniline vajutamine",
    "Hingeldamine ja piiluminе ümber suletud ukse",
    "Kiirustades taskus võtmete otsimine ja kobamine",
    "Kukkuva asja püüdmise üritamine",
    "Üle reageerimine maha läinud joogile särgilt dramaatiliselt pühkides",
    "Logiseva ostukäru ratta küljes range haarde imiteerimine",
    "Avalikus kohas kinnijäänud lukuga kobamine",
    "Komistamine ja tasakaalu taastamine šokeeritud ilmega",
    "Liialdatult kinnijäänud purgikaanega maadlemine",
    "Nähtamatutes kottides meeleheitlik otsimise imiteerimine",
    "Reageerimine uksеlingi kujuteldavale staatilisele šokile",
    "Koputamine ja meeleheitlik kadunud võtmete otsimine",
    "Kujuteldava maha läinud kohvi jõllitamine",
    "Nähtamatu kõrvaklappide juhtme lahtiharutamise võitluse liialdamine",
    "Kukkunud telefoni järele paanikasse sattunud rabelemise imiteerimine",
    "Ootamatu vihmahoo järel läbimärjaks saamise teesklemine",
    "Nähtamatu tõmblemine kangekaelse müügiautomaadiga",
    "Liialdatud üllatus, kui liftιuks sulgub viimasel hetkel",
    "Kadunud rahakoti paaniline otsimine taskutest",
    "Libedal kohal kohmaka komistamise liialdamine",
    "Korduvalt nähtamatu kella kontrollimise imiteerimine",
    "Äkiline reaktsioon ootamatule valjule helile",
    "Ületäidetud portfelli kiirustava sulgemise imiteerimine",
    "Sassis laadijajuhtme lahtiharutamise võitluse liialdamine",
    "Dramaatiline reageerimine väikesele, valulikule paberilõikele",
    "Aevastuse tagasihoidmise teesklemine rahvarohkes ruumis",
    "Ettevaatliku hiilimise imiteerimine, et kedagi mitte äratada",
    "Kergenduse ja paanika liialdamine pärast napilt kukkumise vältimist",
    "Nähtamatu närimiskummi raputamine kingalt",
    "Nähtamatute esemete žongleerimise teesklemine enne ühe kukkumist",
    "Piinlik nägu pärast riietuse äpardust",
    "Kiire, paaniline tants läheneva eseme vältimiseks",
    "Paanikasse sattunud kõne ajal nähtamatu telefoniga kobamine",
    "Ületäitunud kraanikausiga võitlemise liialdamine",
    "Pidevalt libiseva lipsu kiirustava sidumise imiteerimine",
    "Nähtamatute prillide segaduses kohendamise teesklemine",
    "Dramaatiline reaktsioon metalluselt saadud elektrilöögile",
    "Laiali lennanud nähtamatute paberite korjamise liialdamine",
    "Äkiline, liialdatud hüpe nähtamatu heli peale ehmumisel",
    "Kangekaelse autoukse, mis ei avane, kallal kobamise teesklemine",
    "Meeleheitliku tõmbe liialdamine mudasse kinni jäänud kinga vabastamiseks",
    "Paaniline topeltkontroll, kui märkad, et tõmblukk on lahti",
    "Vaikse vaidluse teesklemine mittereageeriva esemega",
    "Ebamugava liigutuse imiteerimine, kui püüad vestlust lõpetada",
    "Meeleheite liialdamine nähtamatu telefoni korduval kontrollimisel sõnumi ootuses",
    "Närvilise, kogeleva reaktsiooni imiteerimine üllatushetkel",
    "Detailse otsingu teesklemine nähtamatu kadunud eseme leidmiseks",
    "Paanika ja uskumatuse liialdamine pärast ootamatut äpardust",
    "Aegluubis reaktsiooni imiteerimine õnnetuse napilt vältimiseks",
    "Nähtamatu raske koorma tasakaalustamise teesklemine, mis äkki ümber kukub",
    "Fedora reguleerimine vihma käes",
    "Nähtamatu sigareti süütamine",
    "Uurides vihjeid tänavalambi all",
    "Monoloog suitsuses baaris",
    "Dramaatiline lennujaamasõit",
    "Piinlik õhtusöögikohtumine",
    "Avalik armastusavaldus",
    "Korvpalli vabavisked",
    "Jalgpalli karistuslöök",
    "Kaalutõstmise võitlus",
    "Kirja kirjutamine koju",
    "Sukeldumine",
    "Haavatud seltsimehe kandmine",
    "Langenud sõduri tervitamine",
    "Kummardus meistrile",
    "Põrgete harjutamine",
    "Mitme vastase blokeerimine",
    "Meditatsioon veeuputuse all",
    "Dramaatiline sulgede kirjutamine",
    "Küünla süütamine pimedas saalis",
    "Hiiglasliku karu kallistamine",
    "Banaanikoore peal libistamine",
    "Jäätise jagamine lemmikloomaga",
    "Kummituse nägemine",
    "Vampiiriks muundumine",
    "Esimene südamevalu",
    "Pakkimine kodust lahkumiseks",
    "Närviline lõpuaktus",
    "Aha hetk",
    "Tõendite esitamine kohtunikule",
    "Vastuväited kohtus",
    "Tunnistajaga konsulteerimine",
    "Kohtuotsuse väljakuulutamine",
    "Eluliste näitajate kontrollimine",
    "Kiirustamine gurney'ga",
    "Tõsiste uudiste edastamine",
    "Taastusravi teostamine",
    "Varude otsimine",
    "Ukse tõkestamine",
    "Ettevaatlik lähenemine varemetes",
    "Väikese valgusallika kaitsmine",
    "Paranoilised pilgud",
    "Reaalsuse tajumise kaotamine",
    "Lukustatud ukse salajane kontrollimine",
    "Gaasivalgusreaktsioon",
    "Power-Up poos",
    "Liialdatud reaktsioon",
    "Sõpruse kõne",
    "Signatuurne rünnakuliigutus",
    "Pump-Action Shotgun'i laadimine",
    "Kiiret autojahti juhtides",
    "Vastutulest kõrvalehoidmine",
    "Ajastatud lõhkeaine paigaldamine",
    "Aardekaardi uurimine",
    "Trossisilla ületamine",
    "Vana templi püüniste vältimine",
    "Võidukas eseme avastamine",
    "Banaanikoorega libisemine",
    "Double Take",
    "Üle võlli naer",
    "Graafiku näitamine",
    "Eksperdi intervjueerimine (kohtus)",
    "Aeglane pisaravõitu vastasseis",
    "Ärevust tekitav kokkuvarisemine",
    "Pikk hüvastijätt",
    "Mõnus aknast vaatamine",
    "Invisible Wall Exploration",
    "Shifting Masks",
    "Walking Backwards in Slow Motion",
    "Audience Interaction",
    "Loitsimine",
    "Mõõga tõmbamine kivist",
    "Draakoniga ratsutamine",
    "Fööniksi kutsumine",
    "Roomamine läbi kummitusmaja",
    "Näriseva ukse avamine",
    "Põgenemine koletise eest",
    "Vaimu poolt vallutatud",
    "Suurendusklaasiga inspekteerimine",
    "Kahtlustatava küsitlemine",
    "Kõigi kogumine salongis",
    "Heureka - vihje ilmsikstulek",
    "Suur avakoor",
    "Tap-Dance Break",
    "Finaalpoos",
    "Kuriteopaiga kindlustamine",
    "Tõendite uurimine UV-valguses",
    "Peakorteri raadioside",
    "Sõrmejälgede tolmutamine",
    "Tunnistuse sulatamine",
    "Meeskonnakaaslase maha hääletamine",
    "Üleliigne ümberkujundamine",
    "Üllatuskatse",
    "Futuristlike nuppude vajutamine",
    "Nulligravitatsiooniline hõljumine",
    "Kohtumine tulnukaga",
    "Ajakäiguhüpe",
    "Dramaatiline löök",
    "Kokkuvarisemine šokeerivatest uudistest",
    "Saladuse ülekuulamine",
    "Kohtumine kurja kaksikuga",
    "Südamepõhjaline jalutuskatse",
    "Pommi kahjutuks tegemine",
    "Salamõrvari eest varjumine",
    "Salapärase vihje leidmine",
    "Fataalse ettekuulutuse saamine",
    "Armastatud inimese leinamine",
    "Enda ohverdamine",
    "Mõistmine, et on liiga hilja",
    "Kõrgete keskpäevade duell",
    "Cowboy-mütsi kallutamine",
    "Lassotrenni",
    "Ratsutamine galopeerival hobusel",
    "Laservõrgustiku ronimine",
    "Seifide lõhkumine",
    "Team Huddle'i planeerimine",
    "Tähelepanu manööver",
    "Närvipingi ühendamine",
    "Ebaseadusliku küberneetika tänavakaubandus",
    "Häkkimine holoekraanil",
    "Ettevõtte droonide põgenemine",
    "Kosmoseremont",
    "Rakettide stardilaskmine",
    "Esimene kontakti käepigistus",
    "Navigeerimine nullgravitatsioonikabiinis",
    "Doors Open Both Ways",
    "Klassikaline rake Gag",
    "Liialdatud kukkumine trepist alla",
    "Redelisse kinni jäämine",
    "Flambee esitlus",
    "Supi degusteerimine ja maitseainete reguleerimine",
    "Köögiviljade tükeldamine suurel kiirusel",
    "Võltsitud isikut tõendava dokumendi näitamine",
    "Secret Hand-Off",
    "Salakuulamine ukse taga",
    "Isikuvahetus",
    "Akende sisselülitamine",
    "Aeglane zombi tassimine",
    "Close Call Bite",
    "Laskemoona otsimine",
    "Raha lugemine tagaruumis",
    "Võimas käepigistusleping",
    "Altkäemaksu pakkumine",
    "Kellegi hirmutamine",
    "Kõiki rõõmsalt tervitada",
    "Puhta keskkonna imetlemine",
    "Täiustatud, vaevatu tehnoloogia kasutamine",
    "Varjatud saladuse ootamatu mõistmine",
    "Isikutunnistuse skaneerimine turvakontrollpunktis",
    "Varjumine jälgimisdroonide eest",
    "Ratsiooni varumine",
    "Reeglite eiramine",
    "Suur tähelaeva sillakomando",
    "Lasermõõgaga vehklemine",
    "Galaktilise ülekande vastuvõtmine",
    "Kuningliku galaktilise suguvõsa paljastamine",
    "Tagasihoidlik vabandus",
    "Üheskoos kinnipeetud",
    "Täielikult keskele sisenemine",
    "Deadpan Delivery While Passing Props",
    "Slow-Motion Group Walk",
    "Täpne teevalmistamine",
    "Suur kummardus neiule",
    "Üle-top-häda-hüüdmine",
    "Kiiresti edasi-tagasi jooksu stseen",
    "Äkiline rühmatants",
    "Romantiline keeris",
    "Dramaatiline vihmatants",
    "Värvide festival",
    "Gadget-kella kontrollimine",
    "Kelmuse põgenemine",
    "Suurepäraste vuntside poleerimine",
    "Kepi koputamine ja mõtlemine",
    "Torusuitsu nuusutamine",
    "Kuriteo kordamine",
    "Korralik tantsimine",
    "Jäme teeserviis",
    "Päikesevarjuga kõndimine",
    "Vihmaga immutatud ülestunnistus",
    "Butler teatab külalistest",
    "Hõbeda poleerimine teenijate ruumides",
    "Õhtusöögiks riietumine",
    "Kuulujuttude kuulamine trepikojast"
];