window.actionsData_en = [
  "Brushing your teeth",
  "Combing or brushing your hair",
  "Washing your face",
  "Taking a shower (washing your body)",
  "Drying off with a towel",
  "Getting dressed (putting on clothes)",
  "Tying your shoelaces",
  "Washing your hands",
  "Eating a meal (using a fork/spoon)",
  "Drinking from a cup",
  "Cooking on a stove (stirring a pot)",
  "Chopping vegetables on a cutting board",
  "Stirring soup in a pot",
  "Flipping pancakes in a pan",
  "Frying an egg in a pan",
  "Tasting food and adding a pinch of salt",
  "Washing dishes in the sink",
  "Drying dishes with a towel",
  "Vacuuming the floor",
  "Sweeping the floor with a broom (pantomime sweeping)",
  "Mopping the floor with a mop",
  "Dusting furniture with a cloth",
  "Wiping a window clean",
  "Taking out the trash (carrying a garbage bag)",
  "Folding laundry (folding clothes)",
  "Ironing clothes on an ironing board",
  "Making the bed (spreading sheets)",
  "Changing a light bulb overhead",
  "Setting the dining table",
  "Feeding a pet (pouring food into a bowl)",
  "Watering plants with a watering can",
  "Raking leaves in the yard",
  "Shoveling snow off a sidewalk",
  "Checking the mailbox for mail",
  "Locking or unlocking a door with a key",
  "Painting a wall with a paint roller",
  "Hammering a nail into a wall",
  "Sawing a piece of wood",
  "Tightening a screw with a screwdriver",
  "Climbing a set of stairs (stepping up)",
  "Reading a book or newspaper",
  "Writing a letter on paper",
  "Knitting with knitting needles",
  "Sewing a button onto fabric",
  "Searching for something under the couch",
  "Changing a baby’s diaper",
  "Pushing a baby stroller",
  "Walking a dog (holding a leash)",
  "Picking up toys from the floor",
  "Applying makeup in a mirror",
  "Shaving your face with a razor",
  "Putting on gloves",
  "Checking the time on a wristwatch",
  "Taking a photo with a smartphone",
  "Calling someone on the phone (holding phone to ear)",
  "Texting on a phone (typing with thumbs)",
  "Opening a stuck jar (struggling to twist the lid)",
  "Using scissors to cut paper",
  "Putting on socks",
  "Buttoning up a shirt",
  "Zipping up a jacket",
  "Pulling open a heavy/stuck door",
  "Pumping gas into a car at a gas station",
  "Paying with cash (handing over money)",
  "Swiping a credit card at a store",
  "Using an ATM machine",
  "Using a vending machine (pressing buttons, retrieving item)",
  "Drinking through a straw",
  "Slurping spaghetti noodles",
  "Chasing after a bus that’s leaving",
  "Watching TV (using a remote to change channels)",
  "Channel surfing (clicking remote repeatedly)",
  "Playing a board game (rolling dice, moving pieces)",
  "Signing a document (writing your signature)",
  "Using a hairdryer to dry hair",
  "Looking in a mirror and adjusting your hair or outfit",
  "Putting in contact lenses",
  "Painting your nails",
  "Hanging a picture frame on a wall (hammering nail)",
  "Playing with a yo-yo",
  "Blowing up a balloon",
  "Popping bubble wrap with your fingers",
  "Hula hooping around your waist",
  "Microwaving food and waiting for it to finish",
  "Tasting something from the fridge and gagging if it’s bad",
  "Tying a necktie around your collar",
  "Running/jogging at a steady pace",
  "Doing jumping jacks",
  "Doing push-ups",
  "Doing pull-ups (imagining a bar overhead)",
  "Lifting weights (bicep curls or lifting a barbell)",
  "Flexing your muscles like a bodybuilder",
  "Stretching in a yoga pose",
  "Doing an aerobics/dance exercise routine",
  "Skipping rope (jump rope)",
  "Riding a bicycle (pedaling and steering)",
  "Swimming (doing a swim stroke)",
  "Diving into a pool (arms overhead, jumping forward)",
  "Skiing downhill (bending knees, using poles)",
  "Ice skating (gliding and balancing with arms out)",
  "Roller skating or rollerblading",
  "Skateboarding (foot kicking and balancing on board)",
  "Surfing on a wave (balancing on an invisible surfboard)",
  "Snowboarding down a slope",
  "Rock climbing a wall (reaching and stepping upward)",
  "Hiking with a heavy backpack",
  "Playing soccer (dribbling and kicking an imaginary ball)",
  "Playing basketball (bouncing an imaginary ball, shooting)",
  "Swinging a baseball bat to hit a ball",
  "Pitching a baseball (winding up and throwing)",
  "Playing tennis (swinging a racket forehand/backhand)",
  "Serving a tennis ball (toss and swing)",
  "Playing volleyball (serving or spiking a ball)",
  "Swinging a golf club to hit a golf ball",
  "Bowling (rolling an invisible bowling ball)",
  "Playing ping pong (table tennis paddle swing)",
  "Throwing a football (American football quarterback throw)",
  "Catching a football pass",
  "Throwing a Frisbee disc",
  "Aiming a bow and shooting an arrow (archery)",
  "Boxing (sparring with fists, punching and guarding)",
  "Karate or martial arts moves (performing a kata or kicks)",
  "Fencing duel (sport sword fighting stance and thrust)",
  "Wrestling an opponent (grappling with air)",
  "Balancing on a balance beam (arms out for balance)",
  "Jumping on a trampoline (bouncing in place)",
  "Playing tug-of-war (pulling an invisible rope hard)",
  "Horseback riding (holding reins and bouncing in saddle)",
  "Riding a mechanical bull (rodeo style, one hand up)",
  "Fishing (casting a rod and reeling in)",
  "Running hurdles (sprinting and jumping an obstacle)",
  "Throwing a javelin",
  "Throwing a shot put (heaving with one shoulder)",
  "Doing a high jump (run and leap)",
  "Punching a boxing speed bag (rapid fists)",
  "Climbing a rope (hand-over-hand climbing motion)",
  "Sledding downhill (sitting and steering imaginary sled)",
  "Having a snowball fight (packing and throwing snowballs)",
  "Playing dodgeball (dodging and throwing a ball)",
  "Playing pool/billiards (lining up a pool cue and shooting)",
  "Rowing a boat (using oars in a rowing motion)",
  "Playing cricket (batting with a cricket bat)",
  "Playing ice hockey (handling a hockey stick and puck)",
  "Playing badminton (swinging a racket underhand to hit a shuttlecock)",
  "Doing a touchdown victory dance (football celebration)",
  "Performing a sumo wrestler’s stomp and stance",
  "Skydiving (free-falling and pulling a parachute ripcord)",
  "Scuba diving (swimming with hand fins and breathing through regulator)",
  "Whitewater rafting (paddling vigorously)",
  "Water skiing (holding a rope handle and balancing on skis)",
  "Sack racing (jumping forward with feet together as if in a sack)",
  "Playing a guitar (strumming and chording)",
  "Playing a piano (pressing keys with both hands)",
  "Playing a violin (bowing with one hand, fingering with the other)",
  "Playing drums (air drumming a drum set)",
  "Playing a flute (holding sideways and moving fingers)",
  "Playing a saxophone (fingering and blowing into sax)",
  "Playing a trumpet (buzzing into mouthpiece, pressing valves)",
  "Singing opera (one hand on chest, dramatic posture)",
  "Singing with a microphone (holding a mic and belting out)",
  "Dancing ballet (graceful spins and arm movements)",
  "Dancing hip-hop style (freestyle dance moves)",
  "Dancing a ballroom waltz (holding an invisible partner)",
  "Dancing disco (pointing fingers in the air, rhythmic steps)",
  "Tap dancing (quick tapping steps)",
  "Breakdancing (doing a wave or a spin on the floor in mime)",
  "Painting a picture on an easel (brushing on canvas)",
  "Drawing on paper (sketching with a pencil)",
  "Sculpting clay (molding clay with hands)",
  "Doing pottery on a potter’s wheel (shaping clay)",
  "Taking photographs with a camera (holding and clicking a camera)",
  "Filming with a video camera (shoulder camera, focusing)",
  "Acting on stage (performing a dramatic monologue or bowing to audience)",
  "Performing a magic trick (e.g., pulling an imaginary rabbit from a hat)",
  "Shuffling a deck of cards (bridge shuffle motion)",
  "Dealing playing cards out",
  "Playing chess (moving an invisible chess piece thoughtfully)",
  "Playing video games (focusing and pressing buttons on a controller)",
  "Knitting a scarf with knitting needles",
  "Using a sewing machine (pumping foot and guiding fabric)",
  "Calligraphy writing with a quill pen",
  "Arranging a bouquet of flowers",
  "Juggling balls (tossing and catching imaginary balls in rhythm)",
  "Juggling clubs or knives (imaginary juggling of dangerous objects)",
  "Walking a tightrope (arms out for balance, careful steps)",
  "Riding a unicycle (arms out, balancing while pedaling one wheel)",
  "Performing as a clown (miming a big smile, silly movements, maybe making a balloon animal)",
  "Mime stuck in an invisible box (classic mime routine, feeling the walls)",
  "Face painting (painting someone’s face with a brush – mimed)",
  "DJ mixing music (pretending to adjust turntables and bob head)",
  "Playing an air guitar (rocking out with no instrument)",
  "Conducting an orchestra (waving a conductor’s baton in time)",
  "Playing an accordion (pushing and pulling, pressing keys)",
  "Folding origami paper (intricately folding an invisible paper)",
  "Lassoing a rope (spinning an imaginary lasso overhead)",
  "Cartooning (drawing a cartoon character on paper)",
  "Performing a stand-up comedy act (delivering jokes with expressive gestures)",
  "Ventriloquism act (moving a dummy puppet’s mouth while 'silent')",
  "Solving a Rubik’s Cube (twisting an invisible cube quickly)",
  "Playing darts (aiming and throwing a dart, then reacting)",
  "Playing hopscotch (hopping through imaginary chalk squares)",
  "Driving a car (steering wheel, shifting gears)",
  "Driving a bus (big steering wheel, opening door lever)",
  "Driving a forklift (operating levers and careful driving)",
  "Flying an airplane (holding a yoke, flipping switches)",
  "Steering a ship (turning a large ship’s wheel)",
  "Digging with a shovel (scooping and tossing dirt)",
  "Hammering a nail (construction work)",
  "Sawing wood with a hand saw",
  "Drilling into a wall with a power drill",
  "Tightening a bolt with a wrench",
  "Operating a jackhammer (vibrating whole body)",
  "Welding metal (miming welding tool and protective visor)",
  "Plunging a toilet (using a plunger vigorously)",
  "Delivering mail (walking and putting mail in boxes)",
  "Milking a cow (sitting on stool, pulling imaginary udders)",
  "Chopping wood with an axe",
  "Driving a tractor on a farm",
  "Herding cattle (whistling and swinging an imaginary lasso)",
  "Typing on a keyboard (rapid finger movements)",
  "Writing on a clipboard or notepad",
  "Answering a phone call (office phone to ear)",
  "Filing documents in a filing cabinet",
  "Making photocopies (pressing copier button, waiting)",
  "Shredding papers in a shredder",
  "Giving a presentation (pointing at imaginary screen or chart)",
  "Mixing chemicals in beakers (scientist role)",
  "Looking through a microscope",
  "Investigating with a magnifying glass (detective role)",
  "Directing traffic (using hand signals to stop/go cars)",
  "Blowing a whistle (referee or police—silent blow, but gesture blowing and point)",
  "Handcuffing a suspect (holding wrists and clicking cuffs)",
  "Writing a parking ticket on a notepad",
  "Saluting (military salute)",
  "Marching in place (soldier drilling)",
  "Scanning someone with a metal detector wand (security guard)",
  "Spraying water from a fire hose (firefighter)",
  "Climbing a ladder (firefighter or worker climbing rungs)",
  "Carrying someone to safety over your shoulder (fireman’s carry with an imaginary person)",
  "Performing surgery (carefully using instruments on a patient)",
  "Listening to a heartbeat with a stethoscope (doctor exam)",
  "Giving an injection with a syringe (nurse or doctor)",
  "Checking a patient’s temperature (thermometer under tongue)",
  "Putting on surgical gloves and mask (snap gloves)",
  "Taking someone’s blood pressure (wrapping cuff, squeezing pump)",
  "Driving an ambulance (sirens wailing motion)",
  "Pulling the whistle cord on a train (locomotive engineer)",
  "Punching tickets on a train (train conductor)",
  "Bartending (shaking a cocktail shaker, pouring into glass)",
  "Pouring a drink from a bottle into a glass",
  "Serving food on a tray (waiter balancing trays)",
  "Stir-frying in a wok (chef tossing food in pan)",
  "Tossing pizza dough in the air (pizzeria chef)",
  "Tasting soup as a chef (sip and approve or add salt)",
  "Cutting hair with scissors and comb (hairdresser)",
  "Using a leaf blower in a yard (gardener)",
  "Mowing the lawn with a push mower",
  "Cutting down a tree with a two-handed saw or axe",
  "Taking photographs at an event (professional photographer with camera)",
  "Giving a speech or lecture (politician or professor gesturing)",
  "Banging a gavel (judge in a courtroom)",
  "Demonstrating safety instructions on an airplane (flight attendant miming seatbelt, oxygen mask)",
  "Floating in zero-gravity as an astronaut (slow movements, tethering self)",
  "Pulling a tooth (dentist wiggling and yanking an invisible tooth, showing it)",
  "Examining a pet (veterinarian checking a dog or cat)",
  "Shelving books (librarian placing books on a high shelf)",
  "Scanning items at a checkout (cashier beeping items)",
  "Using a security wand at airport security (scanning a person)",
  "Working on an assembly line (repeating a task quickly on an imaginary conveyor)",
  "Taking a selfie video for social media (influencer posing with phone)",
  "Arguing a case in court (lawyer gesturing passionately)",
  "Exterminating bugs (spraying insecticide in corners with a tank sprayer)",
  "Communicating in sign language (gesturing as if using ASL)",
  "Packing a box for shipping (taping up a cardboard box)",
  "Performing CPR on a dummy (chest compressions on an invisible person)",
  "Counting money (bank teller flipping through bills)",
  "Waving hello to someone",
  "Waving goodbye enthusiastically",
  "Shaking hands in greeting",
  "Giving someone a big hug",
  "Giving a thumbs-up sign",
  "Giving a thumbs-down sign",
  "Clapping your hands (applause)",
  "High-fiving someone",
  "Fist bumping",
  "Pointing at something in the distance",
  "Beckoning someone to come (waving toward self)",
  "Shrugging your shoulders ('I don’t know')",
  "Nodding your head yes",
  "Shaking your head no",
  "Slapping your forehead (facepalm)",
  "Crossing your arms (looking unimpressed or stubborn)",
  "Tapping your foot impatiently",
  "Putting a finger to your lips ('shh' for quiet)",
  "Covering your ears (not listening or loud noise)",
  "Covering your eyes (scared or surprised)",
  "Covering your mouth in shock (gasping silently)",
  "Rolling your eyes dramatically",
  "Praying (hands together, eyes closed)",
  "Bowing politely or respectfully",
  "Saluting (military style)",
  "Blowing a kiss to someone",
  "Giving a cheek kiss (air kiss greeting)",
  "Wagging your finger in disapproval ('no-no' gesture)",
  "Placing hands on hips (impatient or stern stance)",
  "Stomping your foot in anger",
  "Jumping for joy (leaping up excitedly)",
  "Pumping your fist in celebration ('Yes!')",
  "Wiping away tears while crying",
  "Laughing heartily (holding belly, silent laugh)",
  "Doubling over with laughter",
  "Shivering from cold (rubbing arms, chattering teeth)",
  "Fanning yourself because it’s hot",
  "Coughing into your hand or elbow",
  "Sneezing (ah-choo motion)",
  "Yawning sleepily",
  "Hiccuping (jerking shoulders)",
  "Whistling casually (puckering lips, though no sound)",
  "Staring off daydreaming (head in clouds expression)",
  "Sleepwalking with arms outstretched",
  "Meditating (sitting crossed-legged, eyes closed calmly)",
  "Pressing palms together and bowing (namaste greeting)",
  "Picking your nose (discreetly or comically)",
  "Scratching your head in confusion",
  "Giving someone a piggyback ride (carrying an imaginary person on back)",
  "Playing rock-paper-scissors by yourself (fist and flat hand gestures)",
  "Holding up a hand to say 'stop'",
  "Snapping your fingers to music or in appreciation",
  "Wiggling jazz hands (sparkly fingers wave)",
  "Doing 'the wave' with your arms (like in a stadium)",
  "Signing a signature in the air (to indicate autograph)",
  "Throwing your hands up in exasperation",
  "Putting your hands up as if surrendering",
  "Crossing your fingers for luck",
  "Biting your nails nervously",
  "Pacing back and forth anxiously",
  "Clenching your fists and shaking in anger (trying to contain rage)",
  "Making 'air quotes' with your fingers",
  "Raising one eyebrow skeptically",
  "Making a 'mind blown' gesture (hands exploding away from head)",
  "Slow clapping sarcastically",
  "Flapping your arms and clucking like a chicken",
  "Flying like a bird (flapping wings and soaring)",
  "Imitating an elephant (arm as a trunk, trumpeting silently)",
  "Acting like a monkey (scratching, eating a banana, swinging)",
  "Hopping like a kangaroo (little jumps with hands as small paws)",
  "Jumping like a frog (squat and spring up)",
  "Slithering like a snake (weaving hand or body, hissing silently)",
  "Panting and begging like a dog (tongue out, paws up)",
  "Stretching and preening like a cat (licking paw, arching back)",
  "Swimming like a fish (hands together, wiggling body)",
  "Waddling like a penguin (arms pinned, small steps)",
  "Twitching your nose and hopping like a rabbit",
  "Galloping like a horse (clapping hands to mimic hooves, neigh silently)",
  "Pawing the ground and charging like a bull",
  "Sniffing and oinking like a pig (snout impression)",
  "Buzzing and flying like a bee (using finger as a stinger)",
  "Fluttering like a butterfly (gentle wing motions)",
  "Waddling and quacking like a duck",
  "Crowing like a rooster at dawn (hands as beak)",
  "Leaping out of water like a dolphin",
  "Circling like a shark (dorsal fin hand on head)",
  "Growling and clawing like a bear",
  "Roaring like a lion (silent roar with claws up)",
  "Stalking like a tiger in the jungle",
  "Buzzing around like a mosquito and trying to bite",
  "Beating your chest like a gorilla",
  "Waving arms as tentacles like an octopus",
  "Scuttling sideways like a crab (using hands as pincers)",
  "Squeaking and nibbling like a mouse",
  "Turning your head and hooting like an owl",
  "Howling at the moon like a wolf",
  "Moving slowly like a snail (crawling with one hand as shell)",
  "Soaring like an eagle (arms spread wide)",
  "Crawling slowly like a turtle with a heavy shell",
  "Gobbling and strutting like a turkey",
  "Hanging upside down and flapping like a bat",
  "Coughing up a hairball like a cat",
  "Giving a cat a bath (struggling with an imaginary wet cat)",
  "Staggering like a zombie (arms out, limp walk)",
  "Jerky movements like a robot (stiff arms and legs)",
  "Floating and 'boo!' like a ghost (waving arms, spooky stance)",
  "Pretending to be a vampire (cape over face, fang motion)",
  "Striking a flying superhero pose (one arm out in front)",
  "Landing like a superhero (kneel and fist on ground pose)",
  "Crawling like a baby on all fours",
  "Hobbling like an old person with a cane",
  "Headbutting like a goat",
  "Kicking like a donkey (backward kick motion)",
  "Cackling like a hyena (silent laugh with wild shaking)",
  "Standing on one leg like a flamingo",
  "Chewing cud like a cow (slow chewing, blank stare)",
  "Fanning out an imaginary tail and strutting like a peacock",
  "Inching like an inchworm (using finger to inch along arm)",
  "Moving in slow motion like a sloth",
  "Clapping and barking like a seal (flapping hands together)",
  "Stomping with heavy steps and tiny arms like a T-Rex dinosaur",
  "Trapped in an invisible box (feeling the walls around you)",
  "Pulling an invisible rope (tug-of-war against an unseen force)",
  "Climbing an invisible ladder (reaching up and stepping)",
  "Leaning on an invisible wall (miming a wall for comedic effect)",
  "Walking against a strong wind (pushing forward, body at angle)",
  "Walking on hot coals (tiptoeing quickly, shaking foot in pain)",
  "Slipping on a banana peel (big comedic fall recovery)",
  "Stepping on something sharp (jumping up and hopping in pain)",
  "Carrying a very heavy object (staggering under weight, straining)",
  "Lifting an extremely heavy weight (strongman attempt, shaking arms)",
  "Trying to lift something too heavy and dropping it suddenly",
  "Picking up something that turns out to be very light (overpull and stumble)",
  "Being yanked forward by a big dog on a leash",
  "Chasing your own tail (spinning in circles playfully)",
  "Getting your finger caught in a door (yanking hand back, shaking it)",
  "Swatting at a bee buzzing around you frantically",
  "Discovering gum stuck to the bottom of your shoe (lifting foot, pulling)",
  "Walking on a tightrope high up (arms out, teetering carefully)",
  "Balancing a book on your head while walking",
  "Juggling invisible balls (tossing and catching with no props)",
  "Riding a magic carpet (sitting, steering imaginary carpet)",
  "Flying on a broomstick (as if you’re a witch/wizard flying)",
  "Using a jetpack (strapping on and blasting off, unsteady hover)",
  "Doing the moonwalk dance (gliding backward smoothly)",
  "Running in slow motion (exaggerated slow running and face)",
  "Moving in reverse as if a video is rewinding",
  "Acting like a puppet on strings (jerky, controlled movements from above)",
  "Getting electrocuted comically (shaking and hair standing up)",
  "Blowing up a balloon until it pops (big sudden surprise reaction)",
  "Pretending to shrink down to tiny size (crouching lower, looking up)",
  "Pretending to grow giant (reaching up high, stepping heavy)",
  "Walking through thick jelly or mud (exaggerated resistance in movement)",
  "Defusing a time bomb (carefully clipping wires, tense expressions)",
  "Playing tug-of-war alone (pulling an unseen rope, then being pulled forward)",
  "Floating in zero gravity (slow, drifting movements)",
  "Fighting in slow motion (throwing punches and dodging slowly)",
  "Performing a dramatic faint (hand on forehead, slow collapse)",
  "Opening an imaginary gift box with huge excitement",
  "Eating something extremely spicy (fanning mouth, searching for water)",
  "Tasting something disgusting and trying not to spit it out",
  "Taking a drink and doing a spit-take (spraying out in shock, without actual water)",
  "Walking like an Egyptian (stylized shoulder and arm moves)",
  "Doing a comical double-take (look away, snap back to look again in surprise)",
  "Driving on a bumpy road (jostling up and down in a seat)",
  "Shaking a present to guess what’s inside",
  "Having an uncontrollable sneezing fit",
  "Tying a tie very quickly (hands a blur)",
  "Swatting at flies that just won’t go away (persistent annoyance)",
  "Getting struck by lightning (a sudden jolt, frazzled look)",
  "Walking into an invisible glass door (stop abruptly, rub nose)",
  "Riding a wild rollercoaster (sitting, screaming silently, hands up)",
  "Getting scared by your own reflection in a mirror",
  "Frantically pressing elevator buttons",
  "Gasping and peeking around a closed door",
  "Rushing and fumbling for keys in your pocket",
  "Scrambling to catch something falling",
  "Overreacting to a spilled drink by dramatically wiping your shirt",
  "Miming a tight grip on a wonky shopping cart wheel",
  "Fumbling with a jammed zipper in public",
  "Stumbling and then regaining your balance with a shocked expression",
  "Exaggeratedly twisting a stuck jar lid",
  "Miming a frantic search through invisible bags",
  "Reacting to an imaginary static shock from a doorknob",
  "Pretending to knock and search desperately for lost keys",
  "Gazing in dismay at an imaginary spilled coffee",
  "Overacting the struggle of untangling an invisible headphone cable",
  "Miming a panicked scramble after dropping a phone",
  "Pretending to be drenched after an unexpected downpour",
  "Engaging in an invisible tug-of-war with a stubborn vending machine",
  "Showing exaggerated surprise as an elevator door closes just in time",
  "Miming a frantic check through your pockets for a missing wallet",
  "Overacting a clumsy stumble on an icy patch",
  "Miming the action of repeatedly checking an invisible watch",
  "Reacting with sudden shock to an unexpected loud noise",
  "Miming the hurried closing of an overstuffed briefcase",
  "Exaggerating the struggle of untangling a chaotic charger cable",
  "Dramatically reacting to a tiny, painful paper cut",
  "Pretending to hold back a sneeze in a crowded room",
  "Miming a cautious tiptoe to avoid waking someone",
  "Overacting relief mixed with panic after narrowly avoiding a fall",
  "Shaking off an imaginary piece of gum from your shoe",
  "Pretending to juggle invisible items before one drops",
  "Flashing an embarrassed face after a wardrobe malfunction",
  "Miming a quick, frantic dance to dodge an oncoming object",
  "Fumbling with an imaginary phone during a panicked call",
  "Overacting a frustrated struggle with an overflowing sink",
  "Miming the action of hurriedly tying a tie that keeps slipping",
  "Pretending to adjust an invisible pair of glasses in confusion",
  "Miming a dramatic reaction to receiving a shock from a metal door",
  "Overacting the scramble to pick up scattered invisible papers",
  "Miming a sudden, exaggerated leap when startled by an unseen noise",
  "Pretending to fumble with a stubborn car door that won’t open",
  "Overacting a desperate tug to free a shoe stuck in mud",
  "Miming a frantic double-take when you realize your fly is unzipped",
  "Pretending to engage in a silent argument with an unresponsive object",
  "Miming the awkward shuffle when you’re trying to end a conversation",
  "Overacting the exasperation of repeatedly checking an imaginary phone for a text",
  "Miming a nervous, stuttering reaction when caught off guard",
  "Pretending to mime a detailed search for an invisible misplaced object",
  "Overacting a mix of panic and disbelief after an unexpected mishap",
  "Miming a slow-motion reaction to narrowly avoid an accident",
  "Pretending to balance an invisible heavy load that suddenly tips over"
];
