window.actionsData_et = [
    "Hammaste pesemine",
    "Juuste kammimine või harjamine",
    "Näo pesemine",
    "Duši all käimine (keha pesemine)",
    "Rätikuga kuivatamine",
    "Riietumine (riiete selga panemine)",
    "Kingapaelte sidumine",
    "Käte pesemine",
    "Söömine (kahvli/lusika kasutamine)",
    "Tassist joomine",
    "Pliidil keetmine (poti segamine)",
    "Köögiviljade hakkimine lõikelaual",
    "Supi segamine potis",
    "Pannkookide keeramine pannil",
    "Muna praadimine pannil",
    "Toidu maitsmine ja näpuotsaga soola lisamine",
    "Nõude pesemine kraanikausis",
    "Nõude kuivatamine rätikuga",
    "Tolmuimejaga koristamine",
    "Põranda pühkimine harjaga (pantomiimina pühkimine)",
    "Põranda moppimine",
    "Mööbli tolmust puhastamine lapiga",
    "Akna puhtaks pühkimine",
    "Prügi välja viimine (prügikoti kandmine)",
    "Pesu voltimine (riiete voltimine)",
    "Riiete triikimine triikimislaual",
    "Voodi tegemine (linade laotamine)",
    "Lambipirni vahetamine",
    "Söögilaua katmine",
    "Lemmiklooma toitmine (toidu kaussi valamine)",
    "Taimede kastmine kastekannuga",
    "Lehtede riisumine õues",
    "Lume kõnnitelt kühveldamine",
    "Postkastist kirjade kontrollimine",
    "Ukse lukustamine või avamine võtmega",
    "Seina värvimine värvirulliga",
    "Naela seina löömine haamriga",
    "Puutüki saagimine",
    "Kruvi pingutamine kruvikeerajaga",
    "Trepist üles ronimine (üles astumine)",
    "Raamatu või ajalehe lugemine",
    "Kirja kirjutamine paberile",
    "Kudumine kudumisvarrastega",
    "Nööbi õmblemine kangale",
    "Millegi otsimine diivani alt",
    "Beebi mähkmete vahetamine",
    "Lapsevankri lükkamine",
    "Koeraga jalutamine (rihma hoidmine)",
    "Mänguasjade põrandalt korjamine",
    "Meigi tegemine peegli ees",
    "Näo raseerimine habemenoaga",
    "Kinnaste kätte panemine",
    "Aja kontrollimine käekellalt",
    "Foto tegemine nutitelefoniga",
    "Kellelegi helistamine (telefoni kõrva juures hoidmine)",
    "Telefonil sõnumite saatmine (pöialdega trükkimine)",
    "Kinnijäänud purgi avamine (kaane keeramine)",
    "Kääridega paberi lõikamine",
    "Sokkide jalga panemine",
    "Särgi nööpide kinni panemine",
    "Jaki lukustamine",
    "Raske/kinni jäänud ukse avamine",
    "Bensiini tankimine autosse tanklas",
    "Sularahaga maksmine (raha üle andmine)",
    "Krediitkaardiga tasaarve tegemine",
    "Pangaautomaadi kasutamine",
    "Müügiautomaadi kasutamine (nuppude vajutamine, eseme võtmine)",
    "Kõrrest joomine",
    "Spagetinuudlite sürpimine",
    "Lahkuva bussi järele jooksmine",
    "Teleri vaatamine (puldi kasutamine kanalite vahetamiseks)",
    "Kanalite vahetamine (puldi korduv vajutamine)",
    "Lauamängu mängimine (täringute veeretamine, nupu liigutamine)",
    "Dokumendi allkirjastamine (allkirja kirjutamine)",
    "Fööniga juuste kuivatamine",
    "Peeglis vaatamine ja juuste või riiete kohendamine",
    "Kontaktläätsede paigaldamine",
    "Küünte värvimine",
    "Pildi raami seinale riputamine (naela löömine)",
    "Jojoga mängimine",
    "Õhupalli täis puhumine",
    "Mullipakendi lõhkumine sõrmedega",
    "Huulahuupi vöökohal keerutamine",
    "Toidu soojendamine mikrolaineahjus ja selle lõpetamise ootamine",
    "Millegi maitsmine külmkapist ja oksendamine kui on halb",
    "Lipsu sidumine kraele",
    "Jooksmine/sörkimine ühtlases tempos",
    "Hüpikjalgade tegemine",
    "Kätekõverduste tegemine",
    "Lõuatõmmete tegemine (kujutades kangpuu kohal)",
    "Raskuste tõstmine (biitsepsi kõverdamine või kangi tõstmine)",
    "Lihaste painutamine nagu kulturist",
    "Venitus jooga poosis",
    "Aeroobika/tantsu treeningharjutuste tegemine",
    "Hüppenööriga hüppamine",
    "Jalgrattaga sõitmine (pedaalimine ja juhtimine)",
    "Ujumine (ujumisliigutuse tegemine)",
    "Basseini sukeldumine (käed üleval, ettepoole hüppamine)",
    "Mäest alla suusatamine (põlvede painutamine, keppide kasutamine)",
    "Uisutamine (libisemine ja tasakaalu hoidmine käed väljas)",
    "Rulluisutamine või rulluisutamine",
    "Rulasõit (jalaga lükkamine ja rula peal tasakaalu hoidmine)",
    "Lainel surfamine (nähtamatul surfilaual tasakaalu hoidmine)",
    "Lumelauaga mäest alla sõitmine",
    "Seinal ronimine (ülespoole küünitamine ja astumine)",
    "Matkarada raske seljakotiga",
    "Jalgpalli mängimine (kujuteldava palliga dribbeldamine ja löömine)",
    "Korvpalli mängimine (kujuteldava palli põrgatamine, viskamine)",
    "Pesapallikurika kiigutamine palli löömiseks",
    "Pesapalli viskamine (hoog ja viskamine)",
    "Tennise mängimine (reketiga eeskäe/tagakäe löömine)",
    "Tennisepalli servimine (tõste ja löök)",
    "Võrkpalli mängimine (servimine või palli löömine)",
    "Golfiklubi kiigutamine golfipalli löömiseks",
    "Keegeldamine (nähtamatu keeglipalli veeretamine)",
    "Lauatennise mängimine (lauatennisereketiga löömine)",
    "Ameerika jalgpalli viskamine (ameerika jalgpalli mängijate viskamisstiil)",
    "Jalgpalli söötude vastuvõtmine",
    "Lendtaldrikuga viskamine",
    "Vibuga sihtimiseks ja noole tulistamine (vibu)",
    "Poksimisliigutused (rusikatega löökide tegemine ja kaitsmine)",
    "Karate või võitluskunsti liigutused (kata või löökide sooritamine)",
    "Vehklemisduell (sportvõitlusasend ja torkamine)",
    "Vastasega maadlemine (õhuga haaramine)",
    "Tasakaalutiival tasakaalu hoidmine (käed väljas tasakaalu hoidmiseks)",
    "Batuudil hüppamine (koha peal hüppamine)",
    "Köievedu mängimine (nähtamatu köie tugevalt tõmbamine)",
    "Hobusega ratsutamine (ohjade hoidmine ja sadulas põrkamine)",
    "Mehaanilisel pullil ratsutamine (rodeo stiilis, üks käsi üleval)",
    "Kalapüük (õnge viskamine ja sissekerimine)",
    "Tõkkejooks (sprint ja takistuste ületamine)",
    "Odavise",
    "Kuulitõuge (ühe õlaga tõukamine)",
    "Kõrgushüpe (jooksu ja hüppe sooritamine)",
    "Poksikotile löömine (kiired rusikad)",
    "Köiel ronimine (käsi-käe peale ronimisliigutus)",
    "Kelgutamine mäest alla (kujuteldaval kelgul istumine ja juhtimine)",
    "Lumesõda (lumepallide pakkimine ja viskamine)",
    "Põgenemismäng (põikamine ja palli viskamine)",
    "Piljardi mängimine (kiikee joondamine ja löömine)",
    "Paadiga sõudmine (aerudega sõudmisliigutused)",
    "Kriketi mängimine (löök kriketikurikaga)",
    "Jäähoki mängimine (hokikepi ja litri käsitsemine)",
    "Sulgpalli mängimine (sulgpallireketi altkäega löök)",
    "Touchdown võidutantsu tegemine (ameerika jalgpalli tähistamine)",
    "Sumomaadleja sammu ja asendi sooritamine",
    "Langevarjuhüpe (vaba langemine ja langevarju tõmbamine)",
    "Sukeldumisliigutused (käeliigutused ujumiseks ja hingamine)",
    "Kärestikel parvesõit (jõuline aerutamine)",
    "Veesuusatamine (köie hoidmine ja suuskadel tasakaalu hoidmine)",
    "Kotisjooks (jalad koos edasi hüppamine)",
    "Kitarri mängimine (keelte mängimine ja sõrmitsemine)",
    "Klaveri mängimine (klahvide vajutamine mõlema käega)",
    "Viiuli mängimine (ühe käega poogen, teisega sõrmitsemine)",
    "Trummide mängimine (õhus trummide mängimine)",
    "Flöödi mängimine (külgepidi hoidmine ja sõrmede liigutamine)",
    "Saksofoni mängimine (sõrmitsemine ja saksofoni puhumine)",
    "Trompeti mängimine (huultega puhumise imiteerimine, klappide vajutamine)",
    "Mikrofoniga laulmine (mikrofoni hoidmine ja laulmine)",
    "Balletitants (graatsilised pöörded ja käeliigutused)",
    "Hip-hop tantsustiil (vabas vormis tantsuliigutused)",
    "Ballitantsu valsi tantsimine (nähtamatu partneri hoidmine)",
    "Diskotants (sõrmedega õhus osutamine, rütmilised sammud)",
    "Stepptants (kiired koputavad sammud)",
    "Pildi maalimine molbertil (lõuendil pintseldamine)",
    "Paberil joonistamine (pliiatsiga visandamine)",
    "Saviga skulptuuride tegemine (savi käte vahel voolimine)",
    "Potikedral keraamika tegemine (savi vormimine)",
    "Fotode tegemine kaameraga (kaamera hoidmine ja klõpsamine)",
    "Videokaameraga filmimine (õlal kaamera, fookuse seadmine)",
    "Laval näitlemine (dramaatilise monoloogi esitamine või publikule kummardamine)",
    "Mustkunstitriki sooritamine (nt. nähtamatu jänese kübarast välja tõmbamine)",
    "Kaardipaki segamine (sildamismeetodil)",
    "Mängukaartide jagamine",
    "Male mängimine (nähtamatu malenuppu mõtlikult liigutades)",
    "Videomängude mängimine (keskendunult ja kontrolleril nuppude vajutamine)",
    "Salli kudumine kudumisvarrastega",
    "Õmblusmasina kasutamine (jalaga pumba vajutamine ja kanga juhtimine)",
    "Kalligraafia kirjutamine sulega",
    "Lillekimbu koostamine",
    "Pallidega žongleerimine (kujuteldavate pallide rütmiline viskamine ja püüdmine)",
    "Keppide või nugadega žongleerimine (kujuteldavate ohtlike esemete žongleerimine)",
    "Köiel kõndimine (käed väljas tasakaalu hoidmiseks, ettevaatlikud sammud)",
    "Ührattal sõitmine (käed väljas, tasakaalu hoidmine pedaalides)",
    "Klounina esinemine (pantomiimina suure naeratuse tegemine, naljakad liigutused, võib-olla õhuloom)",
    "Miim nähtamatus kastis (klassikaline miimi rutiin, seinte tunnetamine)",
    "Näomaalingud (kellegi näo värvimine pintsliga – pantomiimina)",
    "DJ muusika miksimisega (kujuteldavate plaadimängijate reguleerimine ja pea õõtsutamine)",
    "Õhukitarri mängima (rocki mängimine ilma pillideta)",
    "Orkestri juhtimine (dirigendi kepiga ajas vehkimine)",
    "Akordioni mängimine (lükkamine ja tõmbamine, klahvide vajutamine)",
    "Origami paberi voltimine (keerukas nähtamatu paberi voltimine)",
    "Lassoga köie keerutamine (kujuteldava lasso pea kohal keerutamine)",
    "Karikatuuride joonistamine (karikatuuri joonistamine paberile)",
    "Stand-up komöödia esitamine (naljde esitamine ilmekate žestidega)",
    "Ventrilokvistmi etendus (nuku suu liigutamine 'vaikselt')",
    "Rubiku kuubiku lahendamine (kujuteldava kuubiku kiire keeramine)",
    "Noolemängu mängimine (sihtmärki sihtides ja noolt visates, seejärel reageerides)",
    "Keksumängu mängimine (kujuteldavatel kriidiga joonistatud ruutudel hüppamine)",
    "Auto juhtimine (rool, käiguvahetus)",
    "Bussi juhtimine (suur rool, ukse avamise hoob)",
    "Kahveltõstuki juhtimine (hoobade käsitsemine ja ettevaatlik juhtimine)",
    "Lennuki juhtimine (juhiste hoidmine, lülitite vajutamine)",
    "Laeva juhtimine (suure laevaratta keeramine)",
    "Labidaga kaevamine (mulla kühveldamine ja viskamine)",
    "Naela löömine haamriga (ehitustöö)",
    "Puidu saagimine käsisaega",
    "Seina puurimine elektrilise puuriga",
    "Poldi pingutamine mutrivõtmega",
    "Pneumaatilise vasara käsitsemine (kogu keha väriseb)",
    "Metalli keevitamine (keevitustööriista ja kaitsemaski pantomiim)",
    "WC ummistuse likvideerimine (jõuliselt kolvi kasutamine)",
    "Posti kättetoimetamine (kõndimine ja kirjade postkasti panemine)",
    "Lehma lüpsmine (istudes ja kujuteldavaid nisasid tõmmates)",
    "Puude raiumine kirvega",
    "Traktoriga sõitmine põllul",
    "Veiste ajamine (vilistatades ja kujuteldava lassoga vehkides)",
    "Klaviatuuril trükkimine (kiired sõrmeliigutused)",
    "Kirjutamine kirjutusalusel või märkmikus",
    "Telefonikõnele vastamine (kontoritelefoni kõrva juures)",
    "Dokumentide registreerimise kabinetis failimisega",
    "Koopiate tegemine (kopeerimismasina nupu vajutamine, ootamine)",
    "Paberite purustamine paberpurustis",
    "Esitluse pidamine (kujuteldavale ekraanile või diagrammile osutamine)",
    "Kemikaalide segamine katseklaasides (teadlase roll)",
    "Mikroskoobi läbi vaatamine",
    "Luubiga uurimine (detektiivi roll)",
    "Liikluse suunamine (käemärkidega autode peatamiseks/liikuma panemiseks)",
    "Vile puhumine (kohtuniku või politsei - vaikne puhumine, kuid vibutava käe žest)",
    "Kahtlusalusele käeraudade panemine (randmete hoidmine ja klõpsutamine)",
    "Parkimistrahvi kirjutamine märkmikusse",
    "Tervitamine (sõjaväeline tervitus)",
    "Koha peal marssimine (sõdur drillil)",
    "Kellegi metalli detektori pulgaga skaneerimine (turvamees)",
    "Veejoa pritsimine tuletõrjevoolikust (tuletõrjuja)",
    "Redelil ronimine (tuletõrjuja või tööline redeli pulkadel ronimas)",
    "Kellegi päästmine oma õlal (tuletõrjuja kanne kujuteldava inimesega)",
    "Operatsiooni sooritamine (operatsiooni ettevaatlik instrumentide kasutamine)",
    "Südamelöögi kuulamine stetoskoobiga (arsti läbivaatus)",
    "Süstiga süsti tegemine (õde või arst)",
    "Patsiendi temperatuuri kontrollimine (termomeeter keele all)",
    "Kirurgiliste kinnaste ja maski paigaldamine (kinnaste pinguldamine)",
    "Kellegi vererõhu mõõtmine (manseti kinnitamine, pumba surumine)",
    "Kiirabi juhtimine (sireenide väljapaistev liigutus)",
    "Rongi vile tõmbamine (vedurijuht)",
    "Piletite augustamine rongis (rongisaatja)",
    "Baarmeni töö (kokteili segamine, klaasi valamine)",
    "Joogipudelist klaasi valamine",
    "Toidu serveerimine kandikul (ettekandja kandikute tasakaalustamine)",
    "Vokkpannil praadimine (kokk tõstab toitu pannil)",
    "Pitsataina õhku viskamine (pitseriakokk)",
    "Supi maitsmine kokana (lonks ja heakskiitmine või soola lisamine)",
    "Juuste lõikamine kääride ja kammiga (juuksur)",
    "Lehepuhuri kasutamine aias (aednik)",
    "Muruniitmine lükatava niidukiga",
    "Puu langetamine kahekäe sae või kirvega",
    "Fotode tegemine üritusel (professionaalne fotograaf kaameraga)",
    "Kõne või loengu pidamine (poliitiku või professori žestid)",
    "Haamri koputamine (kohtunik kohtusaalis)",
    "Lennuki ohutusinstruktsioonide demonstreerimine (stjuardess pantomiimina turvavöö, hapnikumaski)",
    "Nullgravitatsioonis hõljumine astronaudina (aeglased liigutused, enda kinnitamine)",
    "Hamba väljatõmbamine (hambaarst nähtamatu hamba kõigutamine ja tõmbamine, selle näitamine)",
    "Lemmiklooma läbivaatus (loomaarst kontrollib koera või kassi)",
    "Raamatute riiulitele panemine (raamatukoguhoidja paneb raamatuid kõrgele riiulile)",
    "Esemete skaneerimine kassas (kassapidaja piiksutab esemeid)",
    "Turvakontrolli seadme kasutamine lennujaamas (isiku skaneerimine)",
    "Tööstusliini töötamine (kiirelt korduvate liigutuste tegemine kujuteldaval konveieril)",
    "Selfie video tegemine sotsiaalmeedia jaoks (mõjutaja telefoni ees poseerimas)",
    "Putukate hävitamine (putukatõrjevahendi pritsimine nurkadesse)",
    "Viipekeeles suhtlemine (žestide tegemine nagu ASL kasutades)",
    "Paki pakkimine saatmiseks (pappkasti kinni teipimine)",
    "CPR elustamise sooritamine (rindkere surumine nähtamatul isikul)",
    "Raha loendamine (pangatellerina rahatähtede läbi lehitsemine)",
    "Kellelegi suur kallistus andmine",
    "Ennast lehvitav kuna on kuum",
    "Köhimine kätte või küünarnukki",
    "Luksutamine (õlgade tõmbeline liikumine)",
    "Muretult vilistamine (huulte torutamine, kuigi heli pole)",
    "Unistav pilk (pea pilvedes väljendus)",
    "Unes kõndimine väljasirutatud kätega",
    "Kellelegi kukil sõidu andmine (kujuteldav inimene seljas)",
    "Sõrmedega plaksutamine muusikale või tunnustuseks",
    "Käte lehvitamine ja kaagutatmine nagu kana",
    "Lendamine nagu lind (tiibade lehvitamine ja õhku tõusmine)",
    "Lõõtsutamine ja nagu koer kerjamine (keel väljas, käpad üleval)",
    "Venitamine ja kehitamine nagu kass (käpa limpsimine, selja kumerdumine)",
    "Galopeerimine nagu hobune (käsi plaksutades nagu kabjad, hirnumine)",
    "Nuusutamine ja röhkimine nagu siga (kärsa imiteerimine)",
    "Sumisemine ja lendamine nagu mesilane (sõrme kasutades nagu astel)",
    "Lehvitamine nagu liblikas (õrnad tiivalöögi liigutused)",
    "Kukelaulu imiteerimine koidu ajal (käed nokana)",
    "Veest välja hüppamine nagu delfiin",
    "Plaksutamine ja haukumine nagu hüljes (käsi kokku plaksutades)",
    "Rasked sammud ja väikesed käed nagu T-Rex dinosaurus",
    "Lõksus kastis (seinu enda ümber tunnetades)",
    "Köie tõmbamine (köievedu nähtamatu jõu vastu)",
    "Redelil ronimine (ülespoole küünitamine ja astumine)",
    "Seina najal (pantomiimina seina komöödiaefekti jaoks)",
    "Tugeva tuule vastu kõndimine (ettepoole surumine, keha nurga all)",
    "Kuumadel sütel kõndimine (kiiresti varvastele astumine, jala valus raputamine)",
    "Banaanikoorel libastamine (suur koomiline kukkumine ja taastumine)",
    "Millelegi teravale astumine (üles hüppamine ja valus hüplemine)",
    "Väga raske eseme kandmine (kaalualune komistamine, pingutus)",
    "Äärmiselt raske raskuse tõstmine (tugeva mehe katse, värisevad käed)",
    "Katse tõsta midagi liiga rasket ja selle äkiline langemine",
    "Millegi ülestõstmine, mis osutub väga kergeks (ületõmbamine ja komistamine)",
    "Suure koera poolt rihma otsas tõmmatava inimese imiteerimine",
    "Oma saba taga ajamine (mänguliselt ringis keerlemine)",
    "Sõrme ukse vahele jätmine (käe tagasitõmbamine, raputamine)",
    "Paaniliselt enda ümber lendava mesilase peletamine",
    "Kõrgel köiel kõndimine (käed väljas, ettevaatlikult taarumine)",
    "Raamatu pea peal tasakaalustamine kõndides",
    "Pallidega žongleerimine (viskamine ja püüdmine ilma rekvisiitideta)",
    "Võluvaiba peal sõitmine (istumine, kujuteldava vaiba juhtimine)",
    "Nõialuua peal lendamine (justkui oleksid nõid/võlur kes lendab)",
    "Reaktiivseljakoti kasutamine (peale pannes ja õhku tõustes, ebastabiilne hõljumine)",
    "Kuusammu tantsimine (sujuvalt tagurpidi libisemine)",
    "Aegluubis jooksmine (liialdatud aeglane jooksmine ja nägu)",
    "Liikumine tagurpidi nagu video keritakse tagasi",
    "Nagu marionett nööride otsas (katkendlikud, kontrollitud liigutused ülalt)",
    "Koomiliselt elektrilöögi saamine (värisemine ja juuste püsti tõusmine)",
    "Õhupalli täis puhumine kuni see lõhkeb (äkiline üllatusreaktsioon)",
    "Pisikeseks kahanemise teesklemine (kükitamine, üles vaatamine)",
    "Hiiglasliku kasvu teesklemine (kõrgutusse küünitamine, raskelt astumine)",
    "Paksu tarretise või muda läbiminemine (liialdatud vastupanu liikumisel)",
    "Ajapommi lahtiühendamine (ettevaatlikult juhtmeid lõigates, pingeline näoilme)",
    "Üksinda köieveo mängimine (nähtamatut köit tõmmates, seejärel ettepoole tõmmatud olles)",
    "Nullgravitatsioonis hõljumine (aeglased, triivivad liigutused)",
    "Aegluubis võitlemine (aeglaselt lööke andmine ja välja põiklev)",
    "Dramaatilise minestuse sooritamine (käsi laubal, aeglaselt kokku varisemine)",
    "Kujuteldava kingituskasti avamine suure õhinaga",
    "Millegi äärmiselt vürtsika söömine (suu lehvitamine, vee otsimine)",
    "Millegi vastiku maitsmine ja selle väljaköhimise tagasi hoidmine",
    "Joogi võtmine ja selle pritsima (šoki tõttu välja pritsiv, ilma veeta)",
    "Egiptlase moodi kõndimine (stiliseeritud õla ja käte liigutused)",
    "Koomiline topeltvaatus (ära vaatamine, siis üllatusega tagasi vaatamine)",
    "Ebatasasel teel sõitmine (istmekohale üles-alla hüplev)",
    "Kingi raputamine et aimata mis on sees",
    "Kontrollimatu aevastamise hoog",
    "Lipsu väga kiiresti sidumine (käed hägused)",
    "Kärbeste peletamine mis lihtsalt ei lahku (püsiv ärritus)",
    "Pikselöögi saamine (äkiline tõmblus, sassis välimus)",
    "Nähtamatusse klaasukse vastu jalutamine (järsk seisma jäämine, nina hõõrumine)",
    "Metsiku Ameerika mägedel sõitmine (istudes, vaikselt karjudes, käed üleval)",
    "Ehmumine oma peegelpildi ees peeglis",
    "Paaniliselt lifti nuppude vajutamine",
    "Ahmimine ja piiluvune süljetatud ukse tagant",
    "Kiirustamine ja kobamine võtmete järele taskus",
    "Kukkuva asja kinnipüüdmise üritamine",
    "Ülereageerimine peale valatud joogile särgi dramaatilise pühkimisega",
    "Pantomiimina ebakindla ostukorvi ratta hoidmise imiteerimine",
    "Kinnikiilunud luku kobamine avalikus kohas",
    "Komistamine ja tasakaalu taastamine šokeeritud ilmega",
    "Liialdatult kinnikiilunud purgikaanega rabelemise imiteerimine",
    "Nähtamatute kottide sees paaniline otsimine",
    "Ukselingilt staatilise elektri saamise reaktsioon",
    "Koputamise teesklemine ja meeleheitlikult kadunud võtmete otsimine",
    "Kohkunud vaatamine kujuteldavale maha läinud kohvile",
    "Ülemängitud võitlus puntras kõrvaklappide juhtmega",
    "Paaniline rabelemise pantomiim pärast telefoni mahapillamist",
    "Ootamatu vihmast läbimärjaks saamise teesklemine",
    "Tõrkunud müügimasinaga nähtamatu köievedu",
    "Üllatunud nägu kui liftiuks sulgub täpselt õigel ajal",
    "Kadunud rahakoti paaniline kontroll läbi taskute",
    "Kohmaka libastumise ülemängimine jäisel pinnal",
    "Korduvalt nähtamatu kella kontrollimise pantomiim",
    "Ootamatu valju heli peale järsk reaktsioon",
    "Ületäidetud kohvri kiireloomulise sulgemise imiteerimine",
    "Liialdatud võitlus sassis laadijajuhtme lahtiharutamisel",
    "Dramaatiline reageerimine pisikesele paberlõikele",
    "Aevastuse tagasihoidmise teesklemine rahvarohkes ruumis",
    "Ettevaatlikult hiilimise imiteerimine, et mitte kedagi äratada",
    "Ülemängitud kergenduse ja paanika segu pärast napilt kukkumisest pääsemist",
    "Nähtamatu närimiskummi kingalt eemaldamine",
    "Nähtamatute asjade žongleerimise teesklemine kuni üks kukub",
    "Piinliku näo tegemine pärast riietuse korrageminekut",
    "Kiire, paanikast tingitud tantsu imiteerimine lähenevast esemest hoidumiseks",
    "Kujuteldava telefoniga kobamine paanilise kõne ajal",
    "Ülevooluva kraanikausi frustreeritud heitluse ülemängimine",
    "Libiseva lipsu kiireloomulise sidumise pantomiim",
    "Kujuteldavate prillide kohendamine segaduses",
    "Dramaatiline reaktsioon metallustest elektrilöögi saamisel",
    "Ülemängitud pindlaiali lennanud nähtamatute paberite kokkukorjamine",
    "Nähtamatu heli peale ehmatusest järsk, liialdatud hüpe",
    "Tõrksalt mitteavaneva autoukse kobamise teesklemine",
    "Mudasse kinni jäänud kinga meeleheitliku vabastamise ülemängimine",
    "Paanikast tingitud topeltvaatus kui avastad, et luku lukk on lahti",
    "Nähtamatu mittekoopereeruva esemega vaikse vaidluse teesklemine",
    "Ebamugava vestluse lõpetamiskatse imiteeriv kohmetu liikumine",
    "Liialdatud kujuteldava telefoni korduv kontrollimine tekstisõnumi saamiseks",
    "Närvilise, kogeleva reaktsiooni pantomiim kui keegi sind ettevalmistamata tabab",
    "Kujuteldava kadunud eseme üksikasjaliku otsingu imiteerimine",
    "Paanika ja uskmatus segu ülemängimine pärast ootamatut äpardust",
    "Aegluupis reaktsioon õnnetuse napile vältimisele",
    "Nähtamatu raske koorma tasakaalustamise imiteerimine kuni see järsku kaldub",
    "Fedora kohendamine vihmas",
    "Nähtamatu sigareti süütamine",
    "Juhuslik kohtumine peale kogemata maha läinud jooki",
    "Korvpalli vabavisete tegemine",
    "Jalgpalli penalti löömine",
    "Tõstekatsetus",
    "Koju kirja kirjutamine",
    "Varjualusesse sukeldumine",
    "Haavatud kaaslase kandmine",
    "Langenud sõduri tervitamine",
    "Kummardus meistrile",
    "Jalalöökide harjutamine",
    "Mitme vastase blokeerimine",
    "Kinnipitseeritud kirjarulli lugemine",
    "Dramaatiline sulepeaga kirjutamine",
    "Küünla süütamine pimedas saalis",
    "Suure kaisukaru kallistamine",
    "Banaanikoorel libastamine",
    "Jäätise jagamine lemmikloomaga",
    "Kummituse nägemine",
    "Libahundi ulgumine",
    "Kohtusaalis vastuväidete esitamine",
    "Tunnistajaga konsulteerimine",
    "Kohtuotsuse väljakuulutamine",
    "Elutähtsate näitajate kontrollimine",
    "Tõsiste uudiste edastamine",
    "Elustamine",
    "Varustuse otsimine",
    "Ukse barrikadeerimine",
    "Ettevaatlik lähenemine varemetele",
    "Paranoidne pilk",
    "Jõu kogumine",
    "Liialdatud reaktsioon",
    "Allkiri rünnakuliigutus",
    "Pumppüssi laadimine",
    "Kiirel kiirusel auto juhtimine tagaajamisel",
    "Tule eest põiklemine",
    "Ajapommi paigaldamine",
    "Aardekaarti uurimine",
    "Kõikuval köissillal üle minemine",
    "Iidse templi lõksude vältimine",
    "Triumfaalne aarde avastamine",
    "Banaanikoorel libisemine",
    "Liialdatud naer",
    "Koogiga näkku saamine",
    "Graafiku näitamine",
    "Eksperdiga intervjueerimine",
    "Aeglane pisaraterohke vastastikune süüdistamine",
    "Piinatud kokku varisemine",
    "Pikk hüvastijätu-kallistus",
    "Loitsu lausumine",
    "Mõõga kivist välja tõmbamine",
    "Draakonil ratsutamine",
    "Fööniks-linnu väljakutsumine",
    "Kummitusmajast läbi hiilimine",
    "Kriiksuvat ust avades",
    "Koletise eest põgenemine",
    "Vaimu poolt vallatud",
    "Suurendusklaasiga uurimine",
    "Stepptantsu liigutused",
    "Kuriteopaiga turvamine",
    "Tõendite uurimine UV-valguses",
    "Peakorterisse raadio teel teatamine",
    "Sõrmejälgede tolmuga katmine",
    "Liialdatud välimuse muutuse avalikustamine",
    "Dramaatiline laks",
    "Šokeerivate uudiste peale kokku varisemine",
    "Pommi kahjutuks tegemine",
    "Eneseohverdamine",
    "Keskpäevane duell",
    "Kauboi kaabu kohendamine",
    "Lasso harjutamine",
    "Galopeerival hobusel ratsutamine",
    "Laservõrgustiku läbimine",
    "Seifi lahti muukimine",
    "Supi maitsmine ja maitsete kohandamine",
    "Köögiviljade kiire hakkimine",
    "Võltsitud isikutunnistuse näitamine",
    "Ukse taga pealtkuulamine",
    "Akende kinni löömine",
    "Aeglane zombi-kõnnak",
    "Napilt hammustusest pääsemine",
    "Laskemoona otsimine",
    "Raha loendamine tagumises toas",
    "Tugev käepigistus tehingu kinnituseks",
    "Järelevalve drooni eest varjumine",
    "Lasermõõga käsitsemine",
    "Võimsa vuntsi poleerimine",
    "Kepile toetumine ja mõtlemine",
    "Piibusuitsu tõmbamine",
    "Päevavarjuga jalutamine",
    "Hõbeda poleerimine teenijate ruumis",
    "Õhtusöögiks riietumine"
];